In [92]:
import pandas as pd
import numpy as np

In [93]:
df=pd.read_csv(r"D:\code\pyton\Advanced Python\Advanced_python\mobile")

In [94]:
df.head()

,model,price,spec scroe,sim,processor,ram,battery,display,camera,os
0,OnePlus Nord 6,"₹38,999",81,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8s Gen4, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",9000 mAh Battery with 80W Fast Charging,"6.78 inches, 1272 x 2772 px, 165 Hz Display wi...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Android v16
1,Samsung Galaxy S25 Ultra,"₹1,10,000",89,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"6.9 inches, 1440 x 3120 px, 120 Hz Display wit...",200 MP Quad Rear & 12 MP Front Camera,Android v15
2,Vivo T5 Pro,"₹29,999",72,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, IR B...","Snapdragon 7s Gen4, Octa Core Processor","8 GB RAM, 128 GB inbuilt",9020 mAh Battery with 90W Fast Charging,"6.8 inches, 1080 x 2392 px, 120 Hz Display wit...",50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Android v16
3,Samsung Galaxy S25 FE,"₹50,743",77,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Exynos 2400, Deca Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",4900 mAh Battery with 45W Fast Charging,"6.7 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 12 MP + 8 MP Triple Rear & 12 MP Front...,Android v16
4,Vivo T5x 5G,"₹18,999",66,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 7400 Turbo, Octa Core, 2.6 GHz Proce...","6 GB RAM, 128 GB inbuilt",7200 mAh Battery with 44W Fast Charging,"6.76 inches, 1080 x 2344 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Android v16

In [95]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   model       1020 non-null   str
 1   price       1020 non-null   str
 2   spec scroe  1020 non-null   int64
 3   sim         1020 non-null   str
 4   processor   1020 non-null   str
 5   ram         1020 non-null   str
 6   battery     1020 non-null   str
 7   display     1020 non-null   str
 8   camera      1019 non-null   str
 9   os          994 non-null    str
dtypes: int64(1), str(9)
memory usage: 79.8 KB

In [96]:
df.describe()

        spec scroe
count  1020.000000
mean     65.885294
std      14.058394
min       6.000000
25%      57.000000
50%      66.000000
75%      75.250000
max      98.000000

quality issue-

1.model-consistancy

2.price-validity

3.completness

In [97]:
df1=df.copy()

In [98]:
df1.head()

,model,price,spec scroe,sim,processor,ram,battery,display,camera,os
0,OnePlus Nord 6,"₹38,999",81,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8s Gen4, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",9000 mAh Battery with 80W Fast Charging,"6.78 inches, 1272 x 2772 px, 165 Hz Display wi...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Android v16
1,Samsung Galaxy S25 Ultra,"₹1,10,000",89,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"6.9 inches, 1440 x 3120 px, 120 Hz Display wit...",200 MP Quad Rear & 12 MP Front Camera,Android v15
2,Vivo T5 Pro,"₹29,999",72,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, IR B...","Snapdragon 7s Gen4, Octa Core Processor","8 GB RAM, 128 GB inbuilt",9020 mAh Battery with 90W Fast Charging,"6.8 inches, 1080 x 2392 px, 120 Hz Display wit...",50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Android v16
3,Samsung Galaxy S25 FE,"₹50,743",77,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Exynos 2400, Deca Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",4900 mAh Battery with 45W Fast Charging,"6.7 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 12 MP + 8 MP Triple Rear & 12 MP Front...,Android v16
4,Vivo T5x 5G,"₹18,999",66,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 7400 Turbo, Octa Core, 2.6 GHz Proce...","6 GB RAM, 128 GB inbuilt",7200 mAh Battery with 44W Fast Charging,"6.76 inches, 1080 x 2344 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Android v16

In [99]:
df1['price']=df1['price'].str.replace('₹','').str.replace(',','').astype('int')

In [100]:
df1.head()

,model,price,spec scroe,sim,processor,ram,battery,display,camera,os
0,OnePlus Nord 6,38999,81,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8s Gen4, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",9000 mAh Battery with 80W Fast Charging,"6.78 inches, 1272 x 2772 px, 165 Hz Display wi...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Android v16
1,Samsung Galaxy S25 Ultra,110000,89,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"6.9 inches, 1440 x 3120 px, 120 Hz Display wit...",200 MP Quad Rear & 12 MP Front Camera,Android v15
2,Vivo T5 Pro,29999,72,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, IR B...","Snapdragon 7s Gen4, Octa Core Processor","8 GB RAM, 128 GB inbuilt",9020 mAh Battery with 90W Fast Charging,"6.8 inches, 1080 x 2392 px, 120 Hz Display wit...",50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Android v16
3,Samsung Galaxy S25 FE,50743,77,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Exynos 2400, Deca Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",4900 mAh Battery with 45W Fast Charging,"6.7 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 12 MP + 8 MP Triple Rear & 12 MP Front...,Android v16
4,Vivo T5x 5G,18999,66,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 7400 Turbo, Octa Core, 2.6 GHz Proce...","6 GB RAM, 128 GB inbuilt",7200 mAh Battery with 44W Fast Charging,"6.76 inches, 1080 x 2344 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Android v16

In [101]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   model       1020 non-null   str
 1   price       1020 non-null   int64
 2   spec scroe  1020 non-null   int64
 3   sim         1020 non-null   str
 4   processor   1020 non-null   str
 5   ram         1020 non-null   str
 6   battery     1020 non-null   str
 7   display     1020 non-null   str
 8   camera      1019 non-null   str
 9   os          994 non-null    str
dtypes: int64(2), str(8)
memory usage: 79.8 KB

In [102]:
len(df1[df1['price']<=4000])

15

In [103]:
df1=df1[df1['price']>=4000]

In [104]:
df1

,model,price,spec scroe,sim,processor,ram,battery,display,camera,os
0,OnePlus Nord 6,38999,81,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8s Gen4, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",9000 mAh Battery with 80W Fast Charging,"6.78 inches, 1272 x 2772 px, 165 Hz Display wi...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Android v16
1,Samsung Galaxy S25 Ultra,110000,89,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"6.9 inches, 1440 x 3120 px, 120 Hz Display wit...",200 MP Quad Rear & 12 MP Front Camera,Android v15
2,Vivo T5 Pro,29999,72,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, IR B...","Snapdragon 7s Gen4, Octa Core Processor","8 GB RAM, 128 GB inbuilt",9020 mAh Battery with 90W Fast Charging,"6.8 inches, 1080 x 2392 px, 120 Hz Display wit...",50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Android v16
3,Samsung Galaxy S25 FE,50743,77,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Exynos 2400, Deca Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",4900 mAh Battery with 45W Fast Charging,"6.7 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 12 MP + 8 MP Triple Rear & 12 MP Front...,Android v16
4,Vivo T5x 5G,18999,66,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 7400 Turbo, Octa Core, 2.6 GHz Proce...","6 GB RAM, 128 GB inbuilt",7200 mAh Battery with 44W Fast Charging,"6.76 inches, 1080 x 2344 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Android v16
...,...,...,...,...,...,...,...,...,...,...
1015,Realme C85 5G (6GB RAM + 128GB),17999,55,"Dual Sim, 3G, 4G, 5G, Wi-Fi, NFC","Dimensity 6300, Octa Core, 2.4 GHz Processor","6 GB RAM, 128 GB inbuilt",7000 mAh Battery with 45W Fast Charging,"6.8 inches, 720 x 1570 px, 144 Hz Display with...",50 MP Rear & 8 MP Front Camera,Android v15
1016,Vivo X500,57990,83,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Dimensity 9600, Octa Core Processor","12 GB RAM, 256 GB inbuilt",7000 mAh Battery with 90W Fast Charging,"6.67 inches, 1216 x 2640 px, 120 Hz Display wi...",200 MP + 50 MP + 50 MP Triple Rear & 50 MP Fro...,Android v16
1017,Vivo Y19s 5G (4GB RAM + 128GB),13499,50,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 6300, Octa Core, 2.4 GHz Processor","4 GB RAM, 128 GB inbuilt",6000 mAh Battery with 15W Fast Charging,"6.74 inches, 720 x 1600 px, 90 Hz Display with...",13 MP + 0.08 MP Dual Rear & 5 MP Front Camera,Android v15
1018,Oukitel WP60 5G,24699,64,"Dual Sim, 3G, 4G, 5G, Wi-Fi","Dimensity 7025, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",10000 mAh Battery with 33W Fast Charging,"7.2 inches, 720 x 1560 px, 120 Hz Display with...",108 MP + 8 MP + 2 MP Triple Rear & 32 MP Front...,Android v15
1019,Vivo S50,39990,76,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8s Gen3, Octa Core, 3 GHz Processor","12 GB RAM, 256 GB inbuilt",6500 mAh Battery with 100W Fast Charging,"6.59 inches, 1260 x 2750 px, 120 Hz Display wi...",50 MP + 50 MP + 8 MP Triple Rear & 50 MP Front...,Android v16

In [105]:
df1.info()

<class 'pandas.DataFrame'>
Index: 1005 entries, 0 to 1019
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   model       1005 non-null   str
 1   price       1005 non-null   int64
 2   spec scroe  1005 non-null   int64
 3   sim         1005 non-null   str
 4   processor   1005 non-null   str
 5   ram         1005 non-null   str
 6   battery     1005 non-null   str
 7   display     1005 non-null   str
 8   camera      1005 non-null   str
 9   os          989 non-null    str
dtypes: int64(2), str(8)
memory usage: 86.4 KB

In [106]:
df1[df1['os'].isnull()]

,model,price,spec scroe,sim,processor,ram,battery,display,camera,os
185,Oppo Find N6,129990,97,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8 Elite Gen 5, Octa Core, 4.6 GHz P...","12 GB RAM, 256 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.12 inches, 2248 x 2480 px, 120 Hz Display wi...","Foldable Display, Dual Display",NaN
215,Motorola Razr 60 Ultra,79999,98,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Elite, Octa Core, 4.32 GHz Processor","16 GB RAM, 512 GB inbuilt",4700 mAh Battery with 68W Fast Charging,"6.96 inches, 1224 x 2992 px, 165 Hz Display wi...","Foldable Display, Dual Display",NaN
405,Nokia 2780 Flip,4990,25,"Dual Sim, 3G, 4G, Wi-Fi","Snapdragon QM215, Quad Core, 1.3 GHz Processor","512 MB RAM, 4 GB inbuilt",1450 mAh Battery,"2.7 inches, 240 x 320 px Display",Dual Display,NaN
568,Ai+ Nova Flip,39999,76,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",4325 mAh Battery with 45W Fast Charging,"6.78 inches, 1080 x 2640 px, 144 Hz Display wi...","Foldable Display, Dual Display",NaN
587,Huawei Mate 80 Pro,75990,81,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC,...","Kirin 9030, Octa Core Processor","12 GB RAM, 256 GB inbuilt",5750 mAh Battery with 100W Fast Charging,"6.75 inches, 1280 x 2832 px, 144 Hz Display wi...",50 MP + 48 MP + 40 MP Triple Rear & 13 MP Fron...,NaN
591,Samsung Galaxy Z Flip 4 (8GB RAM + 256GB),38350,72,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",NaN
597,HMD Terra M,8999,28,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC","Snapdragon QCM2290, Quad Core, 2 GHz Processor",2510 mAh Battery,"2.8 inches, 240 x 320 px Display",8 MP Rear Camera,"Memory Card Supported, upto 32 GB",NaN
599,Motorola Razr Fold,139999,88,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8 Gen 5, Octa Core, 3.8 GHz Processor",256 GB inbuilt,5200 mAh Battery with Fast Charging,"8.09 inches, 2200 x 2480 px, 120 Hz Display wi...","Foldable Display, Dual Display",NaN
767,Xiaomi 17 Pro,82990,92,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8 Elite Gen 5, Octa Core, 4.6 GHz P...","12 GB RAM, 256 GB inbuilt",6300 mAh Battery with 100W Fast Charging,"6.3 inches, 1220 x 2656 px, 144 Hz Display wit...",Dual Display,NaN
816,Nokia 2660 Flip,4649,15,"Dual Sim, 3G, 4G",Unisoc T107,"48 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.8 inches, 240 x 320 px Display",Dual Display,NaN
895,Nokia 2720 V Flip,6199,22,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 205 , Dual Core, 1.1 GHz Processor","512 MB RAM, 4 GB inbuilt",1500 mAh Battery,"2.8 inches, 240 x 320 px Display",Dual Display,NaN
911,Lava Blaze Duo 3 5G,17999,59,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, IR B...","Dimensity 7060, Octa Core Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",Dual Display,NaN
932,Motorola Razr 70,59990,83,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8S Elite, Octa Core Processor","8 GB RAM, 256 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.9 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",NaN
953,Motorola Razr 60 5G,49999,81,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 7400X, Octa Core, 2.6 GHz Processor","8 GB RAM, 256 GB inbuilt",4500 mAh Battery with 30W Fast Charging,"6.9 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",NaN
962,Samsung Galaxy Z Flip 7 5G,95999,88,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Exynos 2500, Deca Core, 3.3 GHz Processor","12 GB RAM, 256 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...","Foldable Display, Dual Display",NaN
988,Lava Agni 3 5G,20999,67,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 66W Fast Charging,"6.78 inches, 1200 x 2652 px, 120 Hz Display wi...",Dual Display,NaN

In [107]:
df1[df1['model'].str.contains('Apple', na=False, case=False)]

,model,price,spec scroe,sim,processor,ram,battery,display,camera,os
22,Apple iPhone 17,82900,76,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Apple A19, Hexa Core Processor","8 GB RAM, 256 GB inbuilt",3692 mAh Battery with Fast Charging,"6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP Dual Rear & 18 MP Front Camera,iOS v26
57,Apple iPhone 16,69900,70,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A18, Hexa Core, 4.04 GHz Processor","8 GB RAM, 128 GB inbuilt",3561 mAh Battery with Fast Charging,"6.1 inches, 1179 x 2556 px Display with Dynami...",48 MP + 12 MP Dual Rear & 12 MP Front Camera,iOS v18
78,Apple iPhone 17 Pro Max,149900,81,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Apple A19 Pro, Hexa Core Processor","12 GB RAM, 256 GB inbuilt",4832 mAh Battery with Fast Charging,"6.9 inches, 1320 x 2868 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,iOS v26
90,Apple iPhone 15,59900,64,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A16, Hexa Core, 3.46 GHz Processor","6 GB RAM, 128 GB inbuilt",3349 mAh Battery with Fast Charging,"6.1 inches, 1179 x 2556 px Display with Dynami...",48 MP + 12 MP Dual Rear & 12 MP Front Camera,iOS v17
111,Apple iPhone 15 Plus,59994,66,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A16, Hexa Core, 3.46 GHz Processor","6 GB RAM, 128 GB inbuilt",4383 mAh Battery with Fast Charging,"6.7 inches, 1290 x 2796 px Display with Dynami...",48 MP + 12 MP Dual Rear & 12 MP Front Camera,iOS v17
137,Apple iPhone 16 Pro,103990,75,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A18 Pro, Hexa Core, 4.05 GHz Processor","8 GB RAM, 128 GB inbuilt",3582 mAh Battery with Fast Charging,"6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP + 12 MP Triple Rear & 12 MP Fron...,iOS v18
174,Apple iPhone 17 Pro,134900,74,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Apple A19 Pro, Hexa Core Processor","12 GB RAM, 256 GB inbuilt",3988 mAh Battery with Fast Charging,"6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,iOS v26
181,Apple iPhone 13,45690,55,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor","4 GB RAM, 128 GB inbuilt",3240 mAh Battery with Fast Charging,"6.1 inches, 1170 x 2532 px Display with Small ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,iOS v15
198,Apple iPhone 18 Pro Max,179900,77,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","A20 Pro, Octa Core Processor","12 GB RAM, 256 GB inbuilt",5200 mAh Battery with 45W Fast Charging,"6.9 inches, 1800 x 3200 px, 165 Hz Display",200 MP Quad Rear & 32 MP Front Camera,iOS v27
257,Apple iPhone 17e,64900,63,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Apple A19, Hexa Core Processor","8 GB RAM, 256 GB inbuilt",4005 mAh Battery with Fast Charging,"6.1 inches, 1170 x 2532 px Display with Small ...",48 MP Rear & 12 MP Front Camera,iOS v26.3
271,Apple iPhone 18 Pro,139900,72,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Apple A20 Pro,"12 GB RAM, 256 GB inbuilt","6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 48 MP Fron...,iOS v26,iOS v26
274,Apple iPhone Fold,199990,80,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...",Octa Core Processor,"16 GB RAM, 512 GB inbuilt","7.58 inches, 1920 x 2713 px, 120 Hz Display wi...","Foldable Display, Dual Display",48 MP + 48 MP + 48 MP Triple Rear & 24 MP + 24...,iOS v19
301,Apple iPhone Air,94990,64,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Apple A19 Pro, Hexa Core Processor","8 GB RAM, 256 GB inbuilt",3149 mAh Battery with Fast Charging,"6.5 inches, 1260 x 2736 px Display with Dynami...",48 MP Rear & 18 MP Front Camera,iOS v26
306,Apple iPhone 16 Pro Max,127490,80,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A18 Pro, Hexa Core, 4.05 GHz Processor","8 GB RAM, 256 GB inbuilt",4685 mAh Battery with Fast Charging,"6.9 inches, 1320 x 2868 px, 120 Hz Display wit...",48 MP + 48 MP + 12 MP Triple Rear & 12 MP Fron...,iOS v18
337,Apple iPhone 16 Plus,79900,70,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A18, Hexa Core, 4.04 GHz Processor",128 GB inbuilt,4674 mAh Battery with Fast Charging,"6.7 inches, 1290 x 2796 px Display with Dynami...",48 MP + 12 MP Dual Rear & 12 MP Front Camera,iOS v18
358,Apple iPhone 14,52190,58,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor","6 GB RAM, 128 GB inbuilt",3279 mAh Battery with Fast Charging,"6.1 inches, 1170 x 2532 px Display with Small ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,iOS v16
371,Apple iPhone 15 (256GB),69900,64,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A16, Hexa Core, 3.46 GHz Processor","6 GB RAM, 256 GB inbuilt",3349 mAh Battery with Fast Charging,"6.1 inches, 1179 x 2556 px Display with Dynami...",48 MP + 12 MP Dual Rear & 12 MP Front Camera,iOS v17
440,Apple iPhone 16 (256GB),79900,70,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A18, Hexa Core, 4.04 GHz Processor","8 GB RAM, 256 GB inbuilt",3561 mAh Battery with Fast Charging,"6.1 inches, 1179 x 2556 px Display with Dynami...",48 MP + 12 MP Dual Rear & 12 MP Front Camera,iOS v18
453,Apple iPhone 18,89999,67,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Apple A20, Hexa Core Processor","12 GB RAM, 256 GB inbuilt","6.31 inches, 1206 x 2622 px, 120 Hz Display wi...",48 MP + 48 MP Dual Rear & 24 MP Front Camera,iOS v27,iOS v27
460,Apple iPhone 16 Pro (256GB),113490,76,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A18 Pro, Hexa Core, 4.05 GHz Processor","8 GB RAM, 256 GB inbuilt",3582 mAh Battery with Fast Charging,"6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP + 12 MP Triple Rear & 12 MP Fron...,iOS v18
466,Apple iPhone 17 Pro Max (2TB),222990,84,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Apple A19 Pro, Hexa Core Processor","12 GB RAM, 2 TB inbuilt",4832 mAh Battery with Fast Charging,"6.9 inches, 1320 x 2868 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,iOS v26
602,Apple iPhone 17 (512GB),102900,77,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Apple A19, Hexa Core Processor","8 GB RAM, 512 GB inbuilt",3692 mAh Battery with Fast Charging,"6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP Dual Rear & 18 MP Front Camera,iOS v26
662,Apple iPhone 15 Pro,134900,70,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A17 Pro, Hexa Core, 3.78 GHz Processor","8 GB RAM, 128 GB inbuilt",3274 mAh Battery with Fast Charging,"6.1 inches, 1179 x 2556 px, 120 Hz Display wit...",48 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,iOS v17
674,Apple iPhone 17 Pro Max (512GB),169900,83,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Apple A19 Pro, Hexa Core Processor","12 GB RAM, 512 GB inbuilt",4832 mAh Battery with Fast Charging,"6.9 inches, 1320 x 2868 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,iOS v26
675,Apple iPhone 17 Pro Max (1TB),189900,83,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Apple A19 Pro, Hexa Core Processor","12 GB RAM, 1 TB inbuilt",4832 mAh Battery with Fast Charging,"6.9 inches, 1320 x 2868 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,iOS v26
731,Apple iPhone 16e,59900,63,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A18, Hexa Core, 4.04 GHz Processor","8 GB RAM, 128 GB inbuilt",4005 mAh Battery with Fast Charging,"6.1 inches, 1170 x 2532 px Display with Small ...",48 MP Rear & 12 MP Front Camera,iOS v18
755,Apple iPhone 9,29990,40,"Single Sim, 3G, 4G, VoLTE, Wi-Fi, NFC","A13 Bionic, Hexa Core, 2.65 GHz Processor","3 GB RAM, 64 GB inbuilt",2050 mAh Battery with Fast Charging,"4.7 inches, 750 x 1334 px Display with Large N...",12 MP Rear & 7 MP Front Camera,iOS v13.0
790,Apple iPhone 16 Plus (256GB),89900,70,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A18, Hexa Core, 4.04 GHz Processor",256 GB inbuilt,4674 mAh Battery with Fast Charging,"6.7 inches, 1290 x 2796 px Display with Dynami...",48 MP + 12 MP Dual Rear & 12 MP Front Camera,iOS v18
838,Apple iPhone 17 Pro (512GB),149990,74,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Apple A19 Pro, Hexa Core Processor","12 GB RAM, 512 GB inbuilt",3988 mAh Battery with Fast Charging,"6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,iOS v26
885,Apple iPhone 15 Pro Max (1TB),199900,74,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A17 Pro, Hexa Core, 3.78 GHz Processor","8 GB RAM, 1 TB inbuilt",4441 mAh Battery with Fast Charging,"6.7 inches, 1290 x 2796 px, 120 Hz Display wit...",48 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,iOS v17
903,Apple iPhone 18e,69990,62,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Apple A20, Hexa Core Processor","12 GB RAM, 256 GB inbuilt","6.2 inches, 1170 x 2532 px Display",48 MP Rear & 12 MP Front Camera,iOS v27,iOS v27
981,Apple iPhone 17 Plus,99999,66,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Apple A19, Hexa Core Processor","8 GB RAM, 256 GB inbuilt","6.8 inches, 1284 x 3200 px, 120 Hz Display wit...",48 MP + 48 MP Dual Rear & 18 MP Front Camera,iOS v26,iOS v26
1004,Apple iPhone 12 Pro Max,119900,61,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 128 GB inbuilt","6.7 inches, 1284 x 2778 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,iOS v14.0,iOS v14.0
1009,Apple iPhone 17e (512GB),84900,64,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Apple A19, Hexa Core Processor","8 GB RAM, 512 GB inbuilt",4005 mAh Battery with Fast Charging,"6.1 inches, 1170 x 2532 px Display with Small ...",48 MP Rear & 12 MP Front Camera,iOS v26.3

In [108]:
df1.drop([453,271],inplace=True)

In [109]:
df1[df1['model'].str.contains('Apple', na=False, case=False)]

,model,price,spec scroe,sim,processor,ram,battery,display,camera,os
22,Apple iPhone 17,82900,76,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Apple A19, Hexa Core Processor","8 GB RAM, 256 GB inbuilt",3692 mAh Battery with Fast Charging,"6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP Dual Rear & 18 MP Front Camera,iOS v26
57,Apple iPhone 16,69900,70,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A18, Hexa Core, 4.04 GHz Processor","8 GB RAM, 128 GB inbuilt",3561 mAh Battery with Fast Charging,"6.1 inches, 1179 x 2556 px Display with Dynami...",48 MP + 12 MP Dual Rear & 12 MP Front Camera,iOS v18
78,Apple iPhone 17 Pro Max,149900,81,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Apple A19 Pro, Hexa Core Processor","12 GB RAM, 256 GB inbuilt",4832 mAh Battery with Fast Charging,"6.9 inches, 1320 x 2868 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,iOS v26
90,Apple iPhone 15,59900,64,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A16, Hexa Core, 3.46 GHz Processor","6 GB RAM, 128 GB inbuilt",3349 mAh Battery with Fast Charging,"6.1 inches, 1179 x 2556 px Display with Dynami...",48 MP + 12 MP Dual Rear & 12 MP Front Camera,iOS v17
111,Apple iPhone 15 Plus,59994,66,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A16, Hexa Core, 3.46 GHz Processor","6 GB RAM, 128 GB inbuilt",4383 mAh Battery with Fast Charging,"6.7 inches, 1290 x 2796 px Display with Dynami...",48 MP + 12 MP Dual Rear & 12 MP Front Camera,iOS v17
137,Apple iPhone 16 Pro,103990,75,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A18 Pro, Hexa Core, 4.05 GHz Processor","8 GB RAM, 128 GB inbuilt",3582 mAh Battery with Fast Charging,"6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP + 12 MP Triple Rear & 12 MP Fron...,iOS v18
174,Apple iPhone 17 Pro,134900,74,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Apple A19 Pro, Hexa Core Processor","12 GB RAM, 256 GB inbuilt",3988 mAh Battery with Fast Charging,"6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,iOS v26
181,Apple iPhone 13,45690,55,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor","4 GB RAM, 128 GB inbuilt",3240 mAh Battery with Fast Charging,"6.1 inches, 1170 x 2532 px Display with Small ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,iOS v15
198,Apple iPhone 18 Pro Max,179900,77,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","A20 Pro, Octa Core Processor","12 GB RAM, 256 GB inbuilt",5200 mAh Battery with 45W Fast Charging,"6.9 inches, 1800 x 3200 px, 165 Hz Display",200 MP Quad Rear & 32 MP Front Camera,iOS v27
257,Apple iPhone 17e,64900,63,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Apple A19, Hexa Core Processor","8 GB RAM, 256 GB inbuilt",4005 mAh Battery with Fast Charging,"6.1 inches, 1170 x 2532 px Display with Small ...",48 MP Rear & 12 MP Front Camera,iOS v26.3
274,Apple iPhone Fold,199990,80,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...",Octa Core Processor,"16 GB RAM, 512 GB inbuilt","7.58 inches, 1920 x 2713 px, 120 Hz Display wi...","Foldable Display, Dual Display",48 MP + 48 MP + 48 MP Triple Rear & 24 MP + 24...,iOS v19
301,Apple iPhone Air,94990,64,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Apple A19 Pro, Hexa Core Processor","8 GB RAM, 256 GB inbuilt",3149 mAh Battery with Fast Charging,"6.5 inches, 1260 x 2736 px Display with Dynami...",48 MP Rear & 18 MP Front Camera,iOS v26
306,Apple iPhone 16 Pro Max,127490,80,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A18 Pro, Hexa Core, 4.05 GHz Processor","8 GB RAM, 256 GB inbuilt",4685 mAh Battery with Fast Charging,"6.9 inches, 1320 x 2868 px, 120 Hz Display wit...",48 MP + 48 MP + 12 MP Triple Rear & 12 MP Fron...,iOS v18
337,Apple iPhone 16 Plus,79900,70,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A18, Hexa Core, 4.04 GHz Processor",128 GB inbuilt,4674 mAh Battery with Fast Charging,"6.7 inches, 1290 x 2796 px Display with Dynami...",48 MP + 12 MP Dual Rear & 12 MP Front Camera,iOS v18
358,Apple iPhone 14,52190,58,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor","6 GB RAM, 128 GB inbuilt",3279 mAh Battery with Fast Charging,"6.1 inches, 1170 x 2532 px Display with Small ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,iOS v16
371,Apple iPhone 15 (256GB),69900,64,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A16, Hexa Core, 3.46 GHz Processor","6 GB RAM, 256 GB inbuilt",3349 mAh Battery with Fast Charging,"6.1 inches, 1179 x 2556 px Display with Dynami...",48 MP + 12 MP Dual Rear & 12 MP Front Camera,iOS v17
440,Apple iPhone 16 (256GB),79900,70,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A18, Hexa Core, 4.04 GHz Processor","8 GB RAM, 256 GB inbuilt",3561 mAh Battery with Fast Charging,"6.1 inches, 1179 x 2556 px Display with Dynami...",48 MP + 12 MP Dual Rear & 12 MP Front Camera,iOS v18
460,Apple iPhone 16 Pro (256GB),113490,76,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A18 Pro, Hexa Core, 4.05 GHz Processor","8 GB RAM, 256 GB inbuilt",3582 mAh Battery with Fast Charging,"6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP + 12 MP Triple Rear & 12 MP Fron...,iOS v18
466,Apple iPhone 17 Pro Max (2TB),222990,84,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Apple A19 Pro, Hexa Core Processor","12 GB RAM, 2 TB inbuilt",4832 mAh Battery with Fast Charging,"6.9 inches, 1320 x 2868 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,iOS v26
602,Apple iPhone 17 (512GB),102900,77,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Apple A19, Hexa Core Processor","8 GB RAM, 512 GB inbuilt",3692 mAh Battery with Fast Charging,"6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP Dual Rear & 18 MP Front Camera,iOS v26
662,Apple iPhone 15 Pro,134900,70,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A17 Pro, Hexa Core, 3.78 GHz Processor","8 GB RAM, 128 GB inbuilt",3274 mAh Battery with Fast Charging,"6.1 inches, 1179 x 2556 px, 120 Hz Display wit...",48 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,iOS v17
674,Apple iPhone 17 Pro Max (512GB),169900,83,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Apple A19 Pro, Hexa Core Processor","12 GB RAM, 512 GB inbuilt",4832 mAh Battery with Fast Charging,"6.9 inches, 1320 x 2868 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,iOS v26
675,Apple iPhone 17 Pro Max (1TB),189900,83,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Apple A19 Pro, Hexa Core Processor","12 GB RAM, 1 TB inbuilt",4832 mAh Battery with Fast Charging,"6.9 inches, 1320 x 2868 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,iOS v26
731,Apple iPhone 16e,59900,63,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A18, Hexa Core, 4.04 GHz Processor","8 GB RAM, 128 GB inbuilt",4005 mAh Battery with Fast Charging,"6.1 inches, 1170 x 2532 px Display with Small ...",48 MP Rear & 12 MP Front Camera,iOS v18
755,Apple iPhone 9,29990,40,"Single Sim, 3G, 4G, VoLTE, Wi-Fi, NFC","A13 Bionic, Hexa Core, 2.65 GHz Processor","3 GB RAM, 64 GB inbuilt",2050 mAh Battery with Fast Charging,"4.7 inches, 750 x 1334 px Display with Large N...",12 MP Rear & 7 MP Front Camera,iOS v13.0
790,Apple iPhone 16 Plus (256GB),89900,70,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A18, Hexa Core, 4.04 GHz Processor",256 GB inbuilt,4674 mAh Battery with Fast Charging,"6.7 inches, 1290 x 2796 px Display with Dynami...",48 MP + 12 MP Dual Rear & 12 MP Front Camera,iOS v18
838,Apple iPhone 17 Pro (512GB),149990,74,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Apple A19 Pro, Hexa Core Processor","12 GB RAM, 512 GB inbuilt",3988 mAh Battery with Fast Charging,"6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,iOS v26
885,Apple iPhone 15 Pro Max (1TB),199900,74,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A17 Pro, Hexa Core, 3.78 GHz Processor","8 GB RAM, 1 TB inbuilt",4441 mAh Battery with Fast Charging,"6.7 inches, 1290 x 2796 px, 120 Hz Display wit...",48 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,iOS v17
903,Apple iPhone 18e,69990,62,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Apple A20, Hexa Core Processor","12 GB RAM, 256 GB inbuilt","6.2 inches, 1170 x 2532 px Display",48 MP Rear & 12 MP Front Camera,iOS v27,iOS v27
981,Apple iPhone 17 Plus,99999,66,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Apple A19, Hexa Core Processor","8 GB RAM, 256 GB inbuilt","6.8 inches, 1284 x 3200 px, 120 Hz Display wit...",48 MP + 48 MP Dual Rear & 18 MP Front Camera,iOS v26,iOS v26
1004,Apple iPhone 12 Pro Max,119900,61,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 128 GB inbuilt","6.7 inches, 1284 x 2778 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,iOS v14.0,iOS v14.0
1009,Apple iPhone 17e (512GB),84900,64,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Apple A19, Hexa Core Processor","8 GB RAM, 512 GB inbuilt",4005 mAh Battery with Fast Charging,"6.1 inches, 1170 x 2532 px Display with Small ...",48 MP Rear & 12 MP Front Camera,iOS v26.3

In [110]:
df1.drop([274],inplace=True)

In [111]:
df1.drop([597],inplace=True)

In [112]:
df1[df1['model']=='Oppo Find N6']

,model,price,spec scroe,sim,processor,ram,battery,display,camera,os
185,Oppo Find N6,129990,97,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8 Elite Gen 5, Octa Core, 4.6 GHz P...","12 GB RAM, 256 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.12 inches, 2248 x 2480 px, 120 Hz Display wi...","Foldable Display, Dual Display",NaN

In [113]:
df1.loc[185, 'camera'] = "200 MP + 50 MP + 50 MP Triple Rear & 20 MP + 20 MP Dual Front Camera"

In [114]:
df1.loc[215, 'camera'] = "50 MP + 50 MP Dual Rear & 50 MP Front Camera"

In [115]:
df1.loc[591, 'camera'] = "12 MP + 12 MP Dual Rear & 10 MP Front Camera"

In [116]:
df1.loc[767, 'camera'] = "50 MP + 50 MP + 50 MP Triple Rear & 50 MP Front Camera"

In [117]:
df1.loc[767, 'os'] = "Android v16"

In [118]:
df1.drop([405,816,895,],inplace=True)

In [119]:
df1.loc[911, 'camera'] = "50 MP Dual Rear & 8 MP Front Camera"

In [120]:
df1.loc[932, 'camera'] = "50 MP + 50 MP Dual Rear & 32 MP Front Camera"

In [121]:
df1.loc[988, 'camera'] = "50 MP + 8 MP + 8 MP Triple Rear & 16 MP Front Camera"

In [122]:
df1[df1['os'].isnull()]

,model,price,spec scroe,sim,processor,ram,battery,display,camera,os
185,Oppo Find N6,129990,97,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8 Elite Gen 5, Octa Core, 4.6 GHz P...","12 GB RAM, 256 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.12 inches, 2248 x 2480 px, 120 Hz Display wi...",200 MP + 50 MP + 50 MP Triple Rear & 20 MP + 2...,NaN
215,Motorola Razr 60 Ultra,79999,98,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Elite, Octa Core, 4.32 GHz Processor","16 GB RAM, 512 GB inbuilt",4700 mAh Battery with 68W Fast Charging,"6.96 inches, 1224 x 2992 px, 165 Hz Display wi...",50 MP + 50 MP Dual Rear & 50 MP Front Camera,NaN
568,Ai+ Nova Flip,39999,76,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",4325 mAh Battery with 45W Fast Charging,"6.78 inches, 1080 x 2640 px, 144 Hz Display wi...","Foldable Display, Dual Display",NaN
587,Huawei Mate 80 Pro,75990,81,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC,...","Kirin 9030, Octa Core Processor","12 GB RAM, 256 GB inbuilt",5750 mAh Battery with 100W Fast Charging,"6.75 inches, 1280 x 2832 px, 144 Hz Display wi...",50 MP + 48 MP + 40 MP Triple Rear & 13 MP Fron...,NaN
591,Samsung Galaxy Z Flip 4 (8GB RAM + 256GB),38350,72,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,NaN
599,Motorola Razr Fold,139999,88,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8 Gen 5, Octa Core, 3.8 GHz Processor",256 GB inbuilt,5200 mAh Battery with Fast Charging,"8.09 inches, 2200 x 2480 px, 120 Hz Display wi...","Foldable Display, Dual Display",NaN
911,Lava Blaze Duo 3 5G,17999,59,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, IR B...","Dimensity 7060, Octa Core Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP Dual Rear & 8 MP Front Camera,NaN
932,Motorola Razr 70,59990,83,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8S Elite, Octa Core Processor","8 GB RAM, 256 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.9 inches, 1080 x 2640 px, 120 Hz Display wit...",50 MP + 50 MP Dual Rear & 32 MP Front Camera,NaN
953,Motorola Razr 60 5G,49999,81,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 7400X, Octa Core, 2.6 GHz Processor","8 GB RAM, 256 GB inbuilt",4500 mAh Battery with 30W Fast Charging,"6.9 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",NaN
962,Samsung Galaxy Z Flip 7 5G,95999,88,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Exynos 2500, Deca Core, 3.3 GHz Processor","12 GB RAM, 256 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...","Foldable Display, Dual Display",NaN
988,Lava Agni 3 5G,20999,67,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 66W Fast Charging,"6.78 inches, 1200 x 2652 px, 120 Hz Display wi...",50 MP + 8 MP + 8 MP Triple Rear & 16 MP Front ...,NaN

In [123]:
index=[185,215,405,568,591,599,767,816,895,911,932,953,962,988]

In [124]:
df1.info()

<class 'pandas.DataFrame'>
Index: 998 entries, 0 to 1019
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   model       998 non-null    str
 1   price       998 non-null    int64
 2   spec scroe  998 non-null    int64
 3   sim         998 non-null    str
 4   processor   998 non-null    str
 5   ram         998 non-null    str
 6   battery     998 non-null    str
 7   display     998 non-null    str
 8   camera      998 non-null    str
 9   os          987 non-null    str
dtypes: int64(2), str(8)
memory usage: 118.1 KB

In [125]:
df1['camera'].value_counts()

camera
50 MP + 2 MP Dual Rear & 8 MP Front Camera                74
50 MP + 8 MP Dual Rear & 16 MP Front Camera               40
50 MP + 2 MP Dual Rear & 16 MP Front Camera               38
50 MP + 8 MP Dual Rear & 32 MP Front Camera               34
50 MP + 50 MP + 8 MP Triple Rear & 50 MP Front Camera     34
                                                          ..
48 MP + 13 MP + 2 MP Triple Rear & 16 MP Front Camera      1
64 MP Quad Rear & 16 MP Front Camera                       1
iOS v14.0                                                  1
48 MP + 13 MP + 8 MP Triple Rear & 20 MP Front Camera      1
50 MP + 48 MP + 10 MP Triple Rear & 12 MP Front Camera     1
Name: count, Length: 209, dtype: int64

In [126]:
df1['battery'].value_counts()

battery
5000 mAh Battery with 25W Fast Charging                45
5000 mAh Battery with 45W Fast Charging                39
7000 mAh Battery with 80W Fast Charging                37
5000 mAh Battery with 18W Fast Charging                31
5000 mAh Battery with 33W Fast Charging                30
                                                       ..
4500 mAh Battery with 80W Fast Charging                 1
6.7 inches, 1284 x 2778 px Display with Large Notch     1
4000 mAh Battery with 27W Fast Charging                 1
8000 mAh Battery with 800W Fast Charging                1
10000 mAh Battery with 33W Fast Charging                1
Name: count, Length: 254, dtype: int64

In [127]:
df1[df1['battery']=='6.7 inches, 1284 x 2778 px Display with Large Notch']

,model,price,spec scroe,sim,processor,ram,battery,display,camera,os
1004,Apple iPhone 12 Pro Max,119900,61,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 128 GB inbuilt","6.7 inches, 1284 x 2778 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,iOS v14.0,iOS v14.0

In [128]:
df1.loc[1004, 'camera'] = "12 MP + 12 MP + 12 MP Triple Rear & 12 MP Front Camera"

In [129]:
df1.loc[1004, 'battery'] = "3687 mAh"

In [130]:
df1['battery'].value_counts()

battery
5000 mAh Battery with 25W Fast Charging     45
5000 mAh Battery with 45W Fast Charging     39
7000 mAh Battery with 80W Fast Charging     37
5000 mAh Battery with 18W Fast Charging     31
5000 mAh Battery with 33W Fast Charging     30
                                            ..
4500 mAh Battery with 80W Fast Charging      1
3687 mAh                                     1
4000 mAh Battery with 27W Fast Charging      1
8000 mAh Battery with 800W Fast Charging     1
10000 mAh Battery with 33W Fast Charging     1
Name: count, Length: 254, dtype: int64

In [131]:
df1['processor'].value_counts()

processor
Dimensity 6300, Octa Core, 2.4 GHz Processor              120
Octa Core Processor                                        52
Snapdragon 8 Elite Gen 5, Octa Core, 4.6 GHz Processor     26
Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor            24
Dimensity 7400, Octa Core, 2.6 GHz Processor               24
                                                         ...
Exynos 2100, Octa Core, 2.9 GHz Processor                   1
Helio  G95, Octa Core, 2.05 GHz Processor                   1
Bionic A14, Hexa Core, 3.1 GHz Processor                    1
Snapdragon  855, Octa Core, 2.8 GHz Processor               1
Exynos, Deca Core Processor                                 1
Name: count, Length: 225, dtype: int64

In [132]:
df1['display'].value_counts()

display
6.77 inches, 1080 x 2392 px, 120 Hz Display with Punch Hole    50
6.67 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole    46
6.67 inches, 720 x 1604 px, 120 Hz Display with Punch Hole     22
6.75 inches, 720 x 1570 px, 120 Hz Display with Punch Hole     20
6.7 inches, 1080 x 2340 px, 120 Hz Display with Punch Hole     19
                                                               ..
6.74 inches, 720 x 1600 px Display                              1
6.9 inches, 1272 x 2772 px, 120 Hz Display with Punch Hole      1
7.69 inches, 1320 x 2120 px Display with Punch Hole             1
6.67 inches, 1216 x 2640 px, 120 Hz Display with Punch Hole     1
7.2 inches, 720 x 1560 px, 120 Hz Display with Punch Hole       1
Name: count, Length: 292, dtype: int64

In [133]:
df1['ram'].value_counts()

ram
8 GB RAM, 128 GB inbuilt                   219
8 GB RAM, 256 GB inbuilt                   213
12 GB RAM, 256 GB inbuilt                  191
6 GB RAM, 128 GB inbuilt                   125
4 GB RAM, 128 GB inbuilt                    71
4 GB RAM, 64 GB inbuilt                     55
12 GB RAM, 512 GB inbuilt                   44
16 GB RAM, 512 GB inbuilt                   37
16 GB RAM, 256 GB inbuilt                   11
3 GB RAM, 64 GB inbuilt                      5
12 GB RAM, 128 GB inbuilt                    4
6 GB RAM, 256 GB inbuilt                     4
8 GB RAM, 512 GB inbuilt                     3
16 GB RAM, 1 TB inbuilt                      2
2 GB RAM, 64 GB inbuilt                      2
256 GB inbuilt                               2
12 GB RAM, 1 TB inbuilt                      2
128 GB inbuilt                               1
12 GB RAM, 2 TB inbuilt                      1
24 GB RAM, 1 TB inbuilt                      1
256 GB RAM, 128 GB inbuilt                   1
20 GB RAM, 512 GB inbuilt                    1
5100 mAh Battery with 18W Fast Charging      1
8 GB RAM, 1 TB inbuilt                       1
6 GB RAM, 64 GB inbuilt                      1
Name: count, dtype: int64

In [134]:
df1[df1['ram']=='5100 mAh Battery with 18W Fast Charging']

,model,price,spec scroe,sim,processor,ram,battery,display,camera,os
776,Vivo Y04s,7999,39,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","4 GB RAM, 64 GB inbuilt",5100 mAh Battery with 18W Fast Charging,"6.67 inches, 720 x 1600 px, 90 Hz Display with...",13 MP + 2 MP Dual Rear & 5 MP Front Camera,"Memory Card Supported, upto 1 TB",Android v15

In [135]:
df1.drop([776],inplace=True)

In [136]:
df1['ram'].value_counts()

ram
8 GB RAM, 128 GB inbuilt      219
8 GB RAM, 256 GB inbuilt      213
12 GB RAM, 256 GB inbuilt     191
6 GB RAM, 128 GB inbuilt      125
4 GB RAM, 128 GB inbuilt       71
4 GB RAM, 64 GB inbuilt        55
12 GB RAM, 512 GB inbuilt      44
16 GB RAM, 512 GB inbuilt      37
16 GB RAM, 256 GB inbuilt      11
3 GB RAM, 64 GB inbuilt         5
12 GB RAM, 128 GB inbuilt       4
6 GB RAM, 256 GB inbuilt        4
8 GB RAM, 512 GB inbuilt        3
16 GB RAM, 1 TB inbuilt         2
2 GB RAM, 64 GB inbuilt         2
256 GB inbuilt                  2
12 GB RAM, 1 TB inbuilt         2
128 GB inbuilt                  1
12 GB RAM, 2 TB inbuilt         1
24 GB RAM, 1 TB inbuilt         1
256 GB RAM, 128 GB inbuilt      1
20 GB RAM, 512 GB inbuilt       1
8 GB RAM, 1 TB inbuilt          1
6 GB RAM, 64 GB inbuilt         1
Name: count, dtype: int64

In [137]:
df1['sim'].value_counts()

sim
Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi                           238
Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Blaster          200
Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC                      169
Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster               141
Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC                 66
Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC, IR Blaster     54
Dual Sim, 3G, 4G, VoLTE, Wi-Fi                                31
Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi                      24
Dual Sim, 3G, 4G, 5G, Wi-Fi, NFC                              11
Dual Sim, 3G, 4G, VoLTE, Wi-Fi, IR Blaster                    11
Dual Sim, 3G, 4G, Wi-Fi                                       10
Dual Sim, 3G, 4G, 5G, Wi-Fi, NFC, IR Blaster                   8
Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster           7
Dual Sim, 3G, 4G, 5G, Wi-Fi                                    6
Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC                            6
Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster                5
Dual Sim, 3G, 4G, Wi-Fi, NFC, IR Blaster                       3
Dual Sim, 3G, 4G, 5G, Wi-Fi, IR Blaster                        2
3G, 4G, 5G, Wi-Fi, NFC                                         1
Dual Sim, 3G, 4G, Wi-Fi, NFC                                   1
Single Sim, 3G, 4G, VoLTE, Wi-Fi, NFC                          1
3G, 4G, Wi-Fi                                                  1
3G, 4G, Wi-Fi, NFC, IR Blaster                                 1
Name: count, dtype: int64

In [138]:
df1.info()

<class 'pandas.DataFrame'>
Index: 997 entries, 0 to 1019
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   model       997 non-null    str
 1   price       997 non-null    int64
 2   spec scroe  997 non-null    int64
 3   sim         997 non-null    str
 4   processor   997 non-null    str
 5   ram         997 non-null    str
 6   battery     997 non-null    str
 7   display     997 non-null    str
 8   camera      997 non-null    str
 9   os          986 non-null    str
dtypes: int64(2), str(8)
memory usage: 85.7 KB

In [139]:
df1.head()

,model,price,spec scroe,sim,processor,ram,battery,display,camera,os
0,OnePlus Nord 6,38999,81,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8s Gen4, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",9000 mAh Battery with 80W Fast Charging,"6.78 inches, 1272 x 2772 px, 165 Hz Display wi...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Android v16
1,Samsung Galaxy S25 Ultra,110000,89,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"6.9 inches, 1440 x 3120 px, 120 Hz Display wit...",200 MP Quad Rear & 12 MP Front Camera,Android v15
2,Vivo T5 Pro,29999,72,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, IR B...","Snapdragon 7s Gen4, Octa Core Processor","8 GB RAM, 128 GB inbuilt",9020 mAh Battery with 90W Fast Charging,"6.8 inches, 1080 x 2392 px, 120 Hz Display wit...",50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Android v16
3,Samsung Galaxy S25 FE,50743,77,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Exynos 2400, Deca Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",4900 mAh Battery with 45W Fast Charging,"6.7 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 12 MP + 8 MP Triple Rear & 12 MP Front...,Android v16
4,Vivo T5x 5G,18999,66,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 7400 Turbo, Octa Core, 2.6 GHz Proce...","6 GB RAM, 128 GB inbuilt",7200 mAh Battery with 44W Fast Charging,"6.76 inches, 1080 x 2344 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Android v16

In [140]:
brand_name=df1['model'].str.split(' ').str.get(0)

In [141]:
df1.insert(0,'brand_name',brand_name)

In [142]:
df1['brand_name']=df1['brand_name'].str.lower()

In [143]:
df1.head()

,brand_name,model,price,spec scroe,sim,processor,ram,battery,display,camera,os
0,oneplus,OnePlus Nord 6,38999,81,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8s Gen4, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",9000 mAh Battery with 80W Fast Charging,"6.78 inches, 1272 x 2772 px, 165 Hz Display wi...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Android v16
1,samsung,Samsung Galaxy S25 Ultra,110000,89,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"6.9 inches, 1440 x 3120 px, 120 Hz Display wit...",200 MP Quad Rear & 12 MP Front Camera,Android v15
2,vivo,Vivo T5 Pro,29999,72,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, IR B...","Snapdragon 7s Gen4, Octa Core Processor","8 GB RAM, 128 GB inbuilt",9020 mAh Battery with 90W Fast Charging,"6.8 inches, 1080 x 2392 px, 120 Hz Display wit...",50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Android v16
3,samsung,Samsung Galaxy S25 FE,50743,77,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Exynos 2400, Deca Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",4900 mAh Battery with 45W Fast Charging,"6.7 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 12 MP + 8 MP Triple Rear & 12 MP Front...,Android v16
4,vivo,Vivo T5x 5G,18999,66,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 7400 Turbo, Octa Core, 2.6 GHz Proce...","6 GB RAM, 128 GB inbuilt",7200 mAh Battery with 44W Fast Charging,"6.76 inches, 1080 x 2344 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Android v16

In [144]:
has_5g=df1['sim'].str.contains('5G')
has_nfc=df1['sim'].str.contains('NFC')
has_ir=df1['sim'].str.contains('IR Blaster')

In [145]:
df1.insert(5,'has_5G',has_5g)

In [146]:
df1.insert(6,'has_NFC',has_nfc)
df1.insert(7,'has_IR',has_ir)

In [147]:
df1.head()

,brand_name,model,price,spec scroe,sim,has_5G,has_NFC,has_IR,processor,ram,battery,display,camera,os
0,oneplus,OnePlus Nord 6,38999,81,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...",True,True,True,"Snapdragon 8s Gen4, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",9000 mAh Battery with 80W Fast Charging,"6.78 inches, 1272 x 2772 px, 165 Hz Display wi...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Android v16
1,samsung,Samsung Galaxy S25 Ultra,110000,89,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC",True,True,False,"Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"6.9 inches, 1440 x 3120 px, 120 Hz Display wit...",200 MP Quad Rear & 12 MP Front Camera,Android v15
2,vivo,Vivo T5 Pro,29999,72,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, IR B...",True,False,True,"Snapdragon 7s Gen4, Octa Core Processor","8 GB RAM, 128 GB inbuilt",9020 mAh Battery with 90W Fast Charging,"6.8 inches, 1080 x 2392 px, 120 Hz Display wit...",50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Android v16
3,samsung,Samsung Galaxy S25 FE,50743,77,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC",True,True,False,"Exynos 2400, Deca Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",4900 mAh Battery with 45W Fast Charging,"6.7 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 12 MP + 8 MP Triple Rear & 12 MP Front...,Android v16
4,vivo,Vivo T5x 5G,18999,66,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster",True,False,True,"Dimensity 7400 Turbo, Octa Core, 2.6 GHz Proce...","6 GB RAM, 128 GB inbuilt",7200 mAh Battery with 44W Fast Charging,"6.76 inches, 1080 x 2344 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Android v16

In [148]:
processor_name=df1['processor'].str.split(',').str.get(0)

In [149]:
num_core=df1['processor'].str.split(',').str.get(1)

In [150]:
processor_speed=df1['processor'].str.split(',').str.get(2)

In [151]:
df1.head()

,brand_name,model,price,spec scroe,sim,has_5G,has_NFC,has_IR,processor,ram,battery,display,camera,os
0,oneplus,OnePlus Nord 6,38999,81,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...",True,True,True,"Snapdragon 8s Gen4, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",9000 mAh Battery with 80W Fast Charging,"6.78 inches, 1272 x 2772 px, 165 Hz Display wi...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Android v16
1,samsung,Samsung Galaxy S25 Ultra,110000,89,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC",True,True,False,"Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"6.9 inches, 1440 x 3120 px, 120 Hz Display wit...",200 MP Quad Rear & 12 MP Front Camera,Android v15
2,vivo,Vivo T5 Pro,29999,72,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, IR B...",True,False,True,"Snapdragon 7s Gen4, Octa Core Processor","8 GB RAM, 128 GB inbuilt",9020 mAh Battery with 90W Fast Charging,"6.8 inches, 1080 x 2392 px, 120 Hz Display wit...",50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Android v16
3,samsung,Samsung Galaxy S25 FE,50743,77,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC",True,True,False,"Exynos 2400, Deca Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",4900 mAh Battery with 45W Fast Charging,"6.7 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 12 MP + 8 MP Triple Rear & 12 MP Front...,Android v16
4,vivo,Vivo T5x 5G,18999,66,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster",True,False,True,"Dimensity 7400 Turbo, Octa Core, 2.6 GHz Proce...","6 GB RAM, 128 GB inbuilt",7200 mAh Battery with 44W Fast Charging,"6.76 inches, 1080 x 2344 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Android v16

In [237]:
# ১. ভুল বানান এবং সাব-ব্র্যান্ডগুলোকে মেইন ব্র্যান্ডে ম্যাপিং করা
processor_map = {
    'mediatek': 'mediatek', 'helio': 'mediatek', 'dimensit': 'mediatek',
    'bionic': 'apple', 'a13': 'apple',
    'tensor': 'google',
    'tiger': 'unisoc',
    'a20': 'samsung' # (A20 সাধারণত Samsung এর চিপসেট)
}

# ম্যাপিং অ্যাপ্লাই করা
df1['processor_brand'] = df1['processor_brand'].replace(processor_map)

In [234]:
df1.insert(9,'processor_name',processor_name)

ValueError: cannot insert processor_name, already exists

In [153]:
df1.insert(10,'num_core',num_core)

In [154]:
df1.insert(11,'processor_speed',processor_speed)

In [155]:
df1.head()

,brand_name,model,price,spec scroe,sim,has_5G,has_NFC,has_IR,processor,processor_name,num_core,processor_speed,ram,battery,display,camera,os
0,oneplus,OnePlus Nord 6,38999,81,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...",True,True,True,"Snapdragon 8s Gen4, Octa Core, 3.2 GHz Processor",Snapdragon 8s Gen4,Octa Core,3.2 GHz Processor,"8 GB RAM, 256 GB inbuilt",9000 mAh Battery with 80W Fast Charging,"6.78 inches, 1272 x 2772 px, 165 Hz Display wi...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Android v16
1,samsung,Samsung Galaxy S25 Ultra,110000,89,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC",True,True,False,"Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...",Snapdragon 8 Elite for Galaxy,Octa Core,4.47 GHz Processor,"12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"6.9 inches, 1440 x 3120 px, 120 Hz Display wit...",200 MP Quad Rear & 12 MP Front Camera,Android v15
2,vivo,Vivo T5 Pro,29999,72,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, IR B...",True,False,True,"Snapdragon 7s Gen4, Octa Core Processor",Snapdragon 7s Gen4,Octa Core Processor,NaN,"8 GB RAM, 128 GB inbuilt",9020 mAh Battery with 90W Fast Charging,"6.8 inches, 1080 x 2392 px, 120 Hz Display wit...",50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Android v16
3,samsung,Samsung Galaxy S25 FE,50743,77,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC",True,True,False,"Exynos 2400, Deca Core, 3.2 GHz Processor",Exynos 2400,Deca Core,3.2 GHz Processor,"8 GB RAM, 128 GB inbuilt",4900 mAh Battery with 45W Fast Charging,"6.7 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 12 MP + 8 MP Triple Rear & 12 MP Front...,Android v16
4,vivo,Vivo T5x 5G,18999,66,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster",True,False,True,"Dimensity 7400 Turbo, Octa Core, 2.6 GHz Proce...",Dimensity 7400 Turbo,Octa Core,2.6 GHz Processor,"6 GB RAM, 128 GB inbuilt",7200 mAh Battery with 44W Fast Charging,"6.76 inches, 1080 x 2344 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Android v16

In [156]:
processor_brand=df1['processor_name'].str.split(' ').str.get(0)

In [157]:
df1.insert(9,'processor_brand',processor_brand)

In [158]:
df1['processor_brand']=df1['processor_brand'].str.lower()

In [159]:
df1.head()

,brand_name,model,price,spec scroe,sim,has_5G,has_NFC,has_IR,processor,processor_brand,processor_name,num_core,processor_speed,ram,battery,display,camera,os
0,oneplus,OnePlus Nord 6,38999,81,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...",True,True,True,"Snapdragon 8s Gen4, Octa Core, 3.2 GHz Processor",snapdragon,Snapdragon 8s Gen4,Octa Core,3.2 GHz Processor,"8 GB RAM, 256 GB inbuilt",9000 mAh Battery with 80W Fast Charging,"6.78 inches, 1272 x 2772 px, 165 Hz Display wi...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Android v16
1,samsung,Samsung Galaxy S25 Ultra,110000,89,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC",True,True,False,"Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...",snapdragon,Snapdragon 8 Elite for Galaxy,Octa Core,4.47 GHz Processor,"12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"6.9 inches, 1440 x 3120 px, 120 Hz Display wit...",200 MP Quad Rear & 12 MP Front Camera,Android v15
2,vivo,Vivo T5 Pro,29999,72,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, IR B...",True,False,True,"Snapdragon 7s Gen4, Octa Core Processor",snapdragon,Snapdragon 7s Gen4,Octa Core Processor,NaN,"8 GB RAM, 128 GB inbuilt",9020 mAh Battery with 90W Fast Charging,"6.8 inches, 1080 x 2392 px, 120 Hz Display wit...",50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Android v16
3,samsung,Samsung Galaxy S25 FE,50743,77,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC",True,True,False,"Exynos 2400, Deca Core, 3.2 GHz Processor",exynos,Exynos 2400,Deca Core,3.2 GHz Processor,"8 GB RAM, 128 GB inbuilt",4900 mAh Battery with 45W Fast Charging,"6.7 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 12 MP + 8 MP Triple Rear & 12 MP Front...,Android v16
4,vivo,Vivo T5x 5G,18999,66,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster",True,False,True,"Dimensity 7400 Turbo, Octa Core, 2.6 GHz Proce...",dimensity,Dimensity 7400 Turbo,Octa Core,2.6 GHz Processor,"6 GB RAM, 128 GB inbuilt",7200 mAh Battery with 44W Fast Charging,"6.76 inches, 1080 x 2344 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Android v16

In [160]:
df1['num_core'].value_counts()

num_core
Octa Core              827
Octa Core Processor     64
Hexa Core               17
Hexa Core Processor     13
Deca Core               12
Deca Core Processor      2
Nine-Cores               2
Nine Core                1
Single Core              1
1.6 GHz Processor        1
Nine Cores               1
Name: count, dtype: int64

In [161]:
df1[df1['num_core']== ' 1.6 GHz Processor']

,brand_name,model,price,spec scroe,sim,has_5G,has_NFC,has_IR,processor,processor_brand,processor_name,num_core,processor_speed,ram,battery,display,camera,os
541,infinix,Infinix Smart 10 HD,4999,41,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, IR Blaster",False,False,True,"Octa Core, 1.6 GHz Processor",octa,Octa Core,1.6 GHz Processor,NaN,"2 GB RAM, 64 GB inbuilt",5000 mAh Battery with 10W Fast Charging,"6.6 inches, 720 x 1612 px, 90 Hz Display with ...",13 MP Rear & 8 MP Front Camera,Android v14

In [235]:
# ৫৪১ নম্বর ইনডেক্সের জন্য ডাটা ঠিক করা
df1.loc[541, 'num_core'] = 'Octa Core'
df1.loc[541, 'processor_brand'] = np.nan
df1.loc[541, 'processor_name'] = '12nm'
df1.loc[541, 'processor_speed'] = '1.6 GHz Processor'

# চেক করে দেখার জন্য
df1.loc[[541]]

TypeError: Invalid value '1.6 GHz Processor' for dtype 'float64'

In [163]:
df1['num_core'].value_counts()

num_core
 Octa Core              827
 Octa Core Processor     64
 Hexa Core               17
 Hexa Core Processor     13
 Deca Core               12
 Deca Core Processor      2
 Nine-Cores               2
 Nine Core                1
 Single Core              1
Octa Core                 1
 Nine Cores               1
Name: count, dtype: int64

In [164]:
df1['num_core']=df1['num_core'].str.strip()

In [165]:
# ডিকশনারি তৈরি
core_map = {
    'Octa Core Processor': 'Octa Core',
    'Hexa Core Processor': 'Hexa Core',
    'Deca Core Processor': 'Deca Core',
    'Nine-Cores': 'Nine Core'
}

# একবারে সব পরিবর্তন এবং স্পেস ক্লিন করা
df1['num_core'] = df1['num_core'].replace(core_map, regex=True).str.strip()

In [166]:
df1['num_core'].value_counts()

num_core
Octa Core      892
Hexa Core       30
Deca Core       14
Nine Core        3
Single Core      1
Nine Cores       1
Name: count, dtype: int64

In [167]:
# ১. স্প্লিট করে প্রথম অংশটি (সংখ্যা) নেওয়া
df1['processor_speed'] = df1['processor_speed'].str.strip().str.split(' ').str.get(0)

In [168]:
df1['processor_speed']

0        3.2
1       4.47
2        NaN
3        3.2
4        2.6
        ...
1015     2.4
1016     NaN
1017     2.4
1018     2.5
1019       3
Name: processor_speed, Length: 997, dtype: object

In [169]:
df1['processor_speed']=df1['processor_speed'].astype(float)

In [170]:
df1.info()

<class 'pandas.DataFrame'>
Index: 997 entries, 0 to 1019
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   brand_name       997 non-null    object
 1   model            997 non-null    str
 2   price            997 non-null    int64
 3   spec scroe       997 non-null    int64
 4   sim              997 non-null    str
 5   has_5G           997 non-null    bool
 6   has_NFC          997 non-null    bool
 7   has_IR           997 non-null    bool
 8   processor        997 non-null    str
 9   processor_brand  996 non-null    object
 10  processor_name   997 non-null    object
 11  num_core         941 non-null    object
 12  processor_speed  862 non-null    float64
 13  ram              997 non-null    str
 14  battery          997 non-null    str
 15  display          997 non-null    str
 16  camera           997 non-null    str
 17  os               986 non-null    str
dtypes: bool(3), float64(1), int64(2), object(4), str(8)
memory usage: 159.8+ KB

In [171]:
df1.head()

,brand_name,model,price,spec scroe,sim,has_5G,has_NFC,has_IR,processor,processor_brand,processor_name,num_core,processor_speed,ram,battery,display,camera,os
0,oneplus,OnePlus Nord 6,38999,81,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...",True,True,True,"Snapdragon 8s Gen4, Octa Core, 3.2 GHz Processor",snapdragon,Snapdragon 8s Gen4,Octa Core,3.20,"8 GB RAM, 256 GB inbuilt",9000 mAh Battery with 80W Fast Charging,"6.78 inches, 1272 x 2772 px, 165 Hz Display wi...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Android v16
1,samsung,Samsung Galaxy S25 Ultra,110000,89,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC",True,True,False,"Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...",snapdragon,Snapdragon 8 Elite for Galaxy,Octa Core,4.47,"12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"6.9 inches, 1440 x 3120 px, 120 Hz Display wit...",200 MP Quad Rear & 12 MP Front Camera,Android v15
2,vivo,Vivo T5 Pro,29999,72,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, IR B...",True,False,True,"Snapdragon 7s Gen4, Octa Core Processor",snapdragon,Snapdragon 7s Gen4,Octa Core,NaN,"8 GB RAM, 128 GB inbuilt",9020 mAh Battery with 90W Fast Charging,"6.8 inches, 1080 x 2392 px, 120 Hz Display wit...",50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Android v16
3,samsung,Samsung Galaxy S25 FE,50743,77,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC",True,True,False,"Exynos 2400, Deca Core, 3.2 GHz Processor",exynos,Exynos 2400,Deca Core,3.20,"8 GB RAM, 128 GB inbuilt",4900 mAh Battery with 45W Fast Charging,"6.7 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 12 MP + 8 MP Triple Rear & 12 MP Front...,Android v16
4,vivo,Vivo T5x 5G,18999,66,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster",True,False,True,"Dimensity 7400 Turbo, Octa Core, 2.6 GHz Proce...",dimensity,Dimensity 7400 Turbo,Octa Core,2.60,"6 GB RAM, 128 GB inbuilt",7200 mAh Battery with 44W Fast Charging,"6.76 inches, 1080 x 2344 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Android v16

In [172]:
rom=df1['ram'].str.strip().str.split(',').str.get(1)

In [173]:
df1['ram']=df1['ram'].str.strip().str.split(',').str.get(0)

In [174]:
df1['ram']

0        8 GB RAM
1       12 GB RAM
2        8 GB RAM
3        8 GB RAM
4        6 GB RAM
          ...
1015     6 GB RAM
1016    12 GB RAM
1017     4 GB RAM
1018     8 GB RAM
1019    12 GB RAM
Name: ram, Length: 997, dtype: object

In [175]:
df1.insert(14,'memoey',rom)

In [176]:
df1.head()

,brand_name,model,price,spec scroe,sim,has_5G,has_NFC,has_IR,processor,processor_brand,processor_name,num_core,processor_speed,ram,memoey,battery,display,camera,os
0,oneplus,OnePlus Nord 6,38999,81,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...",True,True,True,"Snapdragon 8s Gen4, Octa Core, 3.2 GHz Processor",snapdragon,Snapdragon 8s Gen4,Octa Core,3.20,8 GB RAM,256 GB inbuilt,9000 mAh Battery with 80W Fast Charging,"6.78 inches, 1272 x 2772 px, 165 Hz Display wi...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Android v16
1,samsung,Samsung Galaxy S25 Ultra,110000,89,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC",True,True,False,"Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...",snapdragon,Snapdragon 8 Elite for Galaxy,Octa Core,4.47,12 GB RAM,256 GB inbuilt,5000 mAh Battery with 45W Fast Charging,"6.9 inches, 1440 x 3120 px, 120 Hz Display wit...",200 MP Quad Rear & 12 MP Front Camera,Android v15
2,vivo,Vivo T5 Pro,29999,72,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, IR B...",True,False,True,"Snapdragon 7s Gen4, Octa Core Processor",snapdragon,Snapdragon 7s Gen4,Octa Core,NaN,8 GB RAM,128 GB inbuilt,9020 mAh Battery with 90W Fast Charging,"6.8 inches, 1080 x 2392 px, 120 Hz Display wit...",50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Android v16
3,samsung,Samsung Galaxy S25 FE,50743,77,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC",True,True,False,"Exynos 2400, Deca Core, 3.2 GHz Processor",exynos,Exynos 2400,Deca Core,3.20,8 GB RAM,128 GB inbuilt,4900 mAh Battery with 45W Fast Charging,"6.7 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 12 MP + 8 MP Triple Rear & 12 MP Front...,Android v16
4,vivo,Vivo T5x 5G,18999,66,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster",True,False,True,"Dimensity 7400 Turbo, Octa Core, 2.6 GHz Proce...",dimensity,Dimensity 7400 Turbo,Octa Core,2.60,6 GB RAM,128 GB inbuilt,7200 mAh Battery with 44W Fast Charging,"6.76 inches, 1080 x 2344 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Android v16

In [177]:
df1['ram'].value_counts()

ram
8 GB RAM          436
12 GB RAM         242
6 GB RAM          130
4 GB RAM          126
16 GB RAM          50
3 GB RAM            5
2 GB RAM            2
256 GB inbuilt      2
128 GB inbuilt      1
24 GB RAM           1
256 GB RAM          1
20 GB RAM           1
Name: count, dtype: int64

In [178]:
df1['ram']=df1['ram'].str.strip().str.split(' ').str.get(0).astype(float)

In [179]:
df1['ram'].value_counts()

ram
8.0      436
12.0     242
6.0      130
4.0      126
16.0      50
3.0        5
256.0      3
2.0        2
128.0      1
24.0       1
20.0       1
Name: count, dtype: int64

In [180]:
df1.info()

<class 'pandas.DataFrame'>
Index: 997 entries, 0 to 1019
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   brand_name       997 non-null    object
 1   model            997 non-null    str
 2   price            997 non-null    int64
 3   spec scroe       997 non-null    int64
 4   sim              997 non-null    str
 5   has_5G           997 non-null    bool
 6   has_NFC          997 non-null    bool
 7   has_IR           997 non-null    bool
 8   processor        997 non-null    str
 9   processor_brand  996 non-null    object
 10  processor_name   997 non-null    object
 11  num_core         941 non-null    object
 12  processor_speed  862 non-null    float64
 13  ram              997 non-null    float64
 14  memoey           994 non-null    object
 15  battery          997 non-null    str
 16  display          997 non-null    str
 17  camera           997 non-null    str
 18  os               986 non-null    str
dtypes: bool(3), float64(2), int64(2), object(5), str(7)
memory usage: 167.6+ KB

In [181]:
df1.loc[337, 'ram'] = 8

In [182]:
df1.drop(columns=['memory'], inplace=True)

KeyError: "['memory'] not found in axis"

In [183]:
df1.loc[337, 'memoey'] = '128 GB inbuilt'

In [184]:
df1.loc[[790]]

,brand_name,model,price,spec scroe,sim,has_5G,has_NFC,has_IR,processor,processor_brand,processor_name,num_core,processor_speed,ram,memoey,battery,display,camera,os
790,apple,Apple iPhone 16 Plus (256GB),89900,70,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Bionic A18, Hexa Core, 4.04 GHz Processor",bionic,Bionic A18,Hexa Core,4.04,256.0,NaN,4674 mAh Battery with Fast Charging,"6.7 inches, 1290 x 2796 px Display with Dynami...",48 MP + 12 MP Dual Rear & 12 MP Front Camera,iOS v18

In [185]:
df1.loc[599, 'ram'] = 12
df1.loc[599, 'memoey'] = '256 GB inbuilt'

In [186]:
df1.loc[640, 'ram'] = 8

In [187]:
df1.loc[790, 'ram'] = 8
df1.loc[790, 'memoey'] = '256 GB inbuilt'

In [188]:
df1[df1['ram']>16]

,brand_name,model,price,spec scroe,sim,has_5G,has_NFC,has_IR,processor,processor_brand,processor_name,num_core,processor_speed,ram,memoey,battery,display,camera,os
550,oneplus,OnePlus 13 (24GB RAM+ 1TB),80999,90,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC,...",True,True,True,"Snapdragon 8 Elite, Octa Core, 4.32 GHz Processor",snapdragon,Snapdragon 8 Elite,Octa Core,4.32,24.0,1 TB inbuilt,6000 mAh Battery with 100W Fast Charging,"6.82 inches, 1440 x 3168 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 32 MP Fron...,Android v15
708,huawei,Huawei Mate 80 RS Ultimate,159990,80,"Dual Sim, 3G, 4G, 5G, Wi-Fi, NFC, IR Blaster",True,True,True,Kirin 9030,kirin,Kirin 9030,NaN,NaN,20.0,512 GB inbuilt,6000 mAh Battery with 100W Fast Charging,"6.9 inches, 1320 x 2848 px, 120 Hz Display wit...",50 MP Quad Rear & 13 MP Front Camera,HarmonyOS v6.0

In [189]:
df1['memoey'].value_counts()

memoey
 128 GB inbuilt    420
 256 GB inbuilt    419
 512 GB inbuilt     85
 64 GB inbuilt      63
 1 TB inbuilt        6
256 GB inbuilt       2
128 GB inbuilt       1
 2 TB inbuilt        1
Name: count, dtype: int64

In [190]:
battery_capasity=df1['battery'].str.strip().str.split('with').str.get(0)
fast_charging=df1['battery'].str.strip().str.split('with').str.get(1)

In [191]:
df1.insert(16,'battery_capasity',battery_capasity)

In [192]:
df1.insert(17,'fast_charging',fast_charging)

In [193]:
df1.head()

,brand_name,model,price,spec scroe,sim,has_5G,has_NFC,has_IR,processor,processor_brand,...,num_core,processor_speed,ram,memoey,battery,battery_capasity,fast_charging,display,camera,os
0,oneplus,OnePlus Nord 6,38999,81,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...",True,True,True,"Snapdragon 8s Gen4, Octa Core, 3.2 GHz Processor",snapdragon,...,Octa Core,3.20,8.0,256 GB inbuilt,9000 mAh Battery with 80W Fast Charging,9000 mAh Battery,80W Fast Charging,"6.78 inches, 1272 x 2772 px, 165 Hz Display wi...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Android v16
1,samsung,Samsung Galaxy S25 Ultra,110000,89,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC",True,True,False,"Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...",snapdragon,...,Octa Core,4.47,12.0,256 GB inbuilt,5000 mAh Battery with 45W Fast Charging,5000 mAh Battery,45W Fast Charging,"6.9 inches, 1440 x 3120 px, 120 Hz Display wit...",200 MP Quad Rear & 12 MP Front Camera,Android v15
2,vivo,Vivo T5 Pro,29999,72,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, IR B...",True,False,True,"Snapdragon 7s Gen4, Octa Core Processor",snapdragon,...,Octa Core,NaN,8.0,128 GB inbuilt,9020 mAh Battery with 90W Fast Charging,9020 mAh Battery,90W Fast Charging,"6.8 inches, 1080 x 2392 px, 120 Hz Display wit...",50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Android v16
3,samsung,Samsung Galaxy S25 FE,50743,77,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC",True,True,False,"Exynos 2400, Deca Core, 3.2 GHz Processor",exynos,...,Deca Core,3.20,8.0,128 GB inbuilt,4900 mAh Battery with 45W Fast Charging,4900 mAh Battery,45W Fast Charging,"6.7 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 12 MP + 8 MP Triple Rear & 12 MP Front...,Android v16
4,vivo,Vivo T5x 5G,18999,66,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster",True,False,True,"Dimensity 7400 Turbo, Octa Core, 2.6 GHz Proce...",dimensity,...,Octa Core,2.60,6.0,128 GB inbuilt,7200 mAh Battery with 44W Fast Charging,7200 mAh Battery,44W Fast Charging,"6.76 inches, 1080 x 2344 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Android v16

In [194]:
df1['fast_charging'].value_counts()

fast_charging
45W Fast Charging       157
80W Fast Charging       146
100W Fast Charging       92
25W Fast Charging        86
90W Fast Charging        82
33W Fast Charging        63
15W Fast Charging        53
18W Fast Charging        47
Fast Charging            46
44W Fast Charging        42
120W Fast Charging       37
68W Fast Charging        19
30W Fast Charging        17
60W Fast Charging        16
10W Fast Charging        15
67W Fast Charging        13
50W Fast Charging        11
65W Fast Charging        10
66W Fast Charging         9
35W Fast Charging         4
20W Fast Charging         3
27W Fast Charging         3
150W Fast Charging        2
125W Fast Charging        2
70W Fast Charging         2
444W Fast Charging        1
23W Fast Charging         1
48W Fast Charging         1
55W Fast Charging         1
40W Fast Charging         1
85W Fast Charging         1
11200W Fast Charging      1
320W Fast Charging        1
Small Notch               1
22.5W Fast Charging       1
800W Fast Charging        1
Name: count, dtype: int64

In [195]:
df1.rename(columns={'memoey': 'memory', 'battery_capasity': 'battery_capacity'}, inplace=True)

In [196]:
df1.info()

<class 'pandas.DataFrame'>
Index: 997 entries, 0 to 1019
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   brand_name        997 non-null    object
 1   model             997 non-null    str
 2   price             997 non-null    int64
 3   spec scroe        997 non-null    int64
 4   sim               997 non-null    str
 5   has_5G            997 non-null    bool
 6   has_NFC           997 non-null    bool
 7   has_IR            997 non-null    bool
 8   processor         997 non-null    str
 9   processor_brand   996 non-null    object
 10  processor_name    997 non-null    object
 11  num_core          941 non-null    object
 12  processor_speed   862 non-null    float64
 13  ram               997 non-null    float64
 14  memory            997 non-null    object
 15  battery           997 non-null    str
 16  battery_capacity  997 non-null    object
 17  fast_charging     988 non-null    object
 18  display           997 non-null    str
 19  camera            997 non-null    str
 20  os                986 non-null    str
dtypes: bool(3), float64(2), int64(2), object(7), str(7)
memory usage: 183.2+ KB

In [197]:
df1.head()

,brand_name,model,price,spec scroe,sim,has_5G,has_NFC,has_IR,processor,processor_brand,...,num_core,processor_speed,ram,memory,battery,battery_capacity,fast_charging,display,camera,os
0,oneplus,OnePlus Nord 6,38999,81,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...",True,True,True,"Snapdragon 8s Gen4, Octa Core, 3.2 GHz Processor",snapdragon,...,Octa Core,3.20,8.0,256 GB inbuilt,9000 mAh Battery with 80W Fast Charging,9000 mAh Battery,80W Fast Charging,"6.78 inches, 1272 x 2772 px, 165 Hz Display wi...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Android v16
1,samsung,Samsung Galaxy S25 Ultra,110000,89,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC",True,True,False,"Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...",snapdragon,...,Octa Core,4.47,12.0,256 GB inbuilt,5000 mAh Battery with 45W Fast Charging,5000 mAh Battery,45W Fast Charging,"6.9 inches, 1440 x 3120 px, 120 Hz Display wit...",200 MP Quad Rear & 12 MP Front Camera,Android v15
2,vivo,Vivo T5 Pro,29999,72,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, IR B...",True,False,True,"Snapdragon 7s Gen4, Octa Core Processor",snapdragon,...,Octa Core,NaN,8.0,128 GB inbuilt,9020 mAh Battery with 90W Fast Charging,9020 mAh Battery,90W Fast Charging,"6.8 inches, 1080 x 2392 px, 120 Hz Display wit...",50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Android v16
3,samsung,Samsung Galaxy S25 FE,50743,77,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC",True,True,False,"Exynos 2400, Deca Core, 3.2 GHz Processor",exynos,...,Deca Core,3.20,8.0,128 GB inbuilt,4900 mAh Battery with 45W Fast Charging,4900 mAh Battery,45W Fast Charging,"6.7 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 12 MP + 8 MP Triple Rear & 12 MP Front...,Android v16
4,vivo,Vivo T5x 5G,18999,66,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster",True,False,True,"Dimensity 7400 Turbo, Octa Core, 2.6 GHz Proce...",dimensity,...,Octa Core,2.60,6.0,128 GB inbuilt,7200 mAh Battery with 44W Fast Charging,7200 mAh Battery,44W Fast Charging,"6.76 inches, 1080 x 2344 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Android v16

In [198]:
refrash_rate=df1['display'].str.strip().str.split(',').str.get(2)

In [199]:
df1.insert(19,'refrash_rate',refrash_rate)

In [200]:
df1.head()

,brand_name,model,price,spec scroe,sim,has_5G,has_NFC,has_IR,processor,processor_brand,...,processor_speed,ram,memory,battery,battery_capacity,fast_charging,display,refrash_rate,camera,os
0,oneplus,OnePlus Nord 6,38999,81,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...",True,True,True,"Snapdragon 8s Gen4, Octa Core, 3.2 GHz Processor",snapdragon,...,3.20,8.0,256 GB inbuilt,9000 mAh Battery with 80W Fast Charging,9000 mAh Battery,80W Fast Charging,"6.78 inches, 1272 x 2772 px, 165 Hz Display wi...",165 Hz Display with Punch Hole,50 MP + 8 MP Dual Rear & 32 MP Front Camera,Android v16
1,samsung,Samsung Galaxy S25 Ultra,110000,89,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC",True,True,False,"Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...",snapdragon,...,4.47,12.0,256 GB inbuilt,5000 mAh Battery with 45W Fast Charging,5000 mAh Battery,45W Fast Charging,"6.9 inches, 1440 x 3120 px, 120 Hz Display wit...",120 Hz Display with Punch Hole,200 MP Quad Rear & 12 MP Front Camera,Android v15
2,vivo,Vivo T5 Pro,29999,72,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, IR B...",True,False,True,"Snapdragon 7s Gen4, Octa Core Processor",snapdragon,...,NaN,8.0,128 GB inbuilt,9020 mAh Battery with 90W Fast Charging,9020 mAh Battery,90W Fast Charging,"6.8 inches, 1080 x 2392 px, 120 Hz Display wit...",120 Hz Display with Punch Hole,50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Android v16
3,samsung,Samsung Galaxy S25 FE,50743,77,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC",True,True,False,"Exynos 2400, Deca Core, 3.2 GHz Processor",exynos,...,3.20,8.0,128 GB inbuilt,4900 mAh Battery with 45W Fast Charging,4900 mAh Battery,45W Fast Charging,"6.7 inches, 1080 x 2340 px, 120 Hz Display wit...",120 Hz Display with Punch Hole,50 MP + 12 MP + 8 MP Triple Rear & 12 MP Front...,Android v16
4,vivo,Vivo T5x 5G,18999,66,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster",True,False,True,"Dimensity 7400 Turbo, Octa Core, 2.6 GHz Proce...",dimensity,...,2.60,6.0,128 GB inbuilt,7200 mAh Battery with 44W Fast Charging,7200 mAh Battery,44W Fast Charging,"6.76 inches, 1080 x 2344 px, 120 Hz Display wi...",120 Hz Display with Punch Hole,50 MP + 2 MP Dual Rear & 32 MP Front Camera,Android v16

In [201]:
df1['camera'].value_counts()

camera
50 MP + 2 MP Dual Rear & 8 MP Front Camera                74
50 MP + 8 MP Dual Rear & 16 MP Front Camera               40
50 MP + 2 MP Dual Rear & 16 MP Front Camera               38
50 MP + 8 MP Dual Rear & 32 MP Front Camera               34
50 MP + 50 MP + 8 MP Triple Rear & 50 MP Front Camera     34
                                                          ..
48 MP + 13 MP + 2 MP Triple Rear & 16 MP Front Camera      1
64 MP Quad Rear & 16 MP Front Camera                       1
12 MP + 12 MP + 12 MP Triple Rear & 12 MP Front Camera     1
48 MP + 13 MP + 8 MP Triple Rear & 20 MP Front Camera      1
50 MP + 48 MP + 10 MP Triple Rear & 12 MP Front Camera     1
Name: count, Length: 208, dtype: int64

In [202]:
df1.head()

,brand_name,model,price,spec scroe,sim,has_5G,has_NFC,has_IR,processor,processor_brand,...,processor_speed,ram,memory,battery,battery_capacity,fast_charging,display,refrash_rate,camera,os
0,oneplus,OnePlus Nord 6,38999,81,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...",True,True,True,"Snapdragon 8s Gen4, Octa Core, 3.2 GHz Processor",snapdragon,...,3.20,8.0,256 GB inbuilt,9000 mAh Battery with 80W Fast Charging,9000 mAh Battery,80W Fast Charging,"6.78 inches, 1272 x 2772 px, 165 Hz Display wi...",165 Hz Display with Punch Hole,50 MP + 8 MP Dual Rear & 32 MP Front Camera,Android v16
1,samsung,Samsung Galaxy S25 Ultra,110000,89,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC",True,True,False,"Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...",snapdragon,...,4.47,12.0,256 GB inbuilt,5000 mAh Battery with 45W Fast Charging,5000 mAh Battery,45W Fast Charging,"6.9 inches, 1440 x 3120 px, 120 Hz Display wit...",120 Hz Display with Punch Hole,200 MP Quad Rear & 12 MP Front Camera,Android v15
2,vivo,Vivo T5 Pro,29999,72,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, IR B...",True,False,True,"Snapdragon 7s Gen4, Octa Core Processor",snapdragon,...,NaN,8.0,128 GB inbuilt,9020 mAh Battery with 90W Fast Charging,9020 mAh Battery,90W Fast Charging,"6.8 inches, 1080 x 2392 px, 120 Hz Display wit...",120 Hz Display with Punch Hole,50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Android v16
3,samsung,Samsung Galaxy S25 FE,50743,77,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC",True,True,False,"Exynos 2400, Deca Core, 3.2 GHz Processor",exynos,...,3.20,8.0,128 GB inbuilt,4900 mAh Battery with 45W Fast Charging,4900 mAh Battery,45W Fast Charging,"6.7 inches, 1080 x 2340 px, 120 Hz Display wit...",120 Hz Display with Punch Hole,50 MP + 12 MP + 8 MP Triple Rear & 12 MP Front...,Android v16
4,vivo,Vivo T5x 5G,18999,66,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster",True,False,True,"Dimensity 7400 Turbo, Octa Core, 2.6 GHz Proce...",dimensity,...,2.60,6.0,128 GB inbuilt,7200 mAh Battery with 44W Fast Charging,7200 mAh Battery,44W Fast Charging,"6.76 inches, 1080 x 2344 px, 120 Hz Display wi...",120 Hz Display with Punch Hole,50 MP + 2 MP Dual Rear & 32 MP Front Camera,Android v16

In [203]:
rear_part = df1['camera'].str.split(' ').str.get(0)

# 'errors=coerce' দিলে 'Foldable' এর মতো শব্দগুলো NaN হয়ে যাবে, এরর দিবে না
rear_camera = pd.to_numeric(rear_part, errors='coerce')

# ২. Front Camera আলাদা করা
front_part = df1['camera'].str.split('&').str.get(1).str.strip().str.split(' ').str.get(0)
front_camera = pd.to_numeric(front_part, errors='coerce')

In [204]:
df1.drop(columns=['rear_camera','front_camera'], inplace=True)

KeyError: "['rear_camera', 'front_camera'] not found in axis"

In [205]:
df1.insert(21,'rear_camera',rear_camera)
df1.insert(22,'front_camera',front_camera)

In [206]:
# ব্যাটারি থেকে শুধু সংখ্যাটি নেওয়া (যেমন: 9000 mAh -> 9000)
df1['battery_capacity'] = df1['battery_capacity'].str.split(' ').str.get(0).astype(float)

# ফাস্ট চার্জিং থেকে সংখ্যা নেওয়া (যেমন: 80W -> 80)
df1['fast_charging'] = df1['fast_charging'].str.extract('(\d+)').astype(float)

<>:5: SyntaxWarning: invalid escape sequence '\d'
<>:5: SyntaxWarning: invalid escape sequence '\d'
C:\Users\DELL\AppData\Local\Temp\ipykernel_25956\3673254891.py:5: SyntaxWarning: invalid escape sequence '\d'
  df1['fast_charging'] = df1['fast_charging'].str.extract('(\d+)').astype(float)

In [207]:
df1.rename(columns={'battery_capacity': 'battery_capacity(mAh)', 'fast_charging': 'fast_charging(W)'}, inplace=True)

In [208]:
screeen_size=df1['display'].str.strip().str.split(',').str.get(0)

In [209]:
df1.insert(18,'screeen_size',screeen_size)

In [210]:
df1.drop(columns=['display'],inplace=True)

In [211]:
df1.head()

,brand_name,model,price,spec scroe,sim,has_5G,has_NFC,has_IR,processor,processor_brand,...,memory,battery,battery_capacity(mAh),fast_charging(W),screeen_size,refrash_rate,camera,rear_camera,front_camera,os
0,oneplus,OnePlus Nord 6,38999,81,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...",True,True,True,"Snapdragon 8s Gen4, Octa Core, 3.2 GHz Processor",snapdragon,...,256 GB inbuilt,9000 mAh Battery with 80W Fast Charging,9000.0,80.0,6.78 inches,165 Hz Display with Punch Hole,50 MP + 8 MP Dual Rear & 32 MP Front Camera,50.0,32.0,Android v16
1,samsung,Samsung Galaxy S25 Ultra,110000,89,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC",True,True,False,"Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...",snapdragon,...,256 GB inbuilt,5000 mAh Battery with 45W Fast Charging,5000.0,45.0,6.9 inches,120 Hz Display with Punch Hole,200 MP Quad Rear & 12 MP Front Camera,200.0,12.0,Android v15
2,vivo,Vivo T5 Pro,29999,72,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, IR B...",True,False,True,"Snapdragon 7s Gen4, Octa Core Processor",snapdragon,...,128 GB inbuilt,9020 mAh Battery with 90W Fast Charging,9020.0,90.0,6.8 inches,120 Hz Display with Punch Hole,50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,50.0,50.0,Android v16
3,samsung,Samsung Galaxy S25 FE,50743,77,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC",True,True,False,"Exynos 2400, Deca Core, 3.2 GHz Processor",exynos,...,128 GB inbuilt,4900 mAh Battery with 45W Fast Charging,4900.0,45.0,6.7 inches,120 Hz Display with Punch Hole,50 MP + 12 MP + 8 MP Triple Rear & 12 MP Front...,50.0,12.0,Android v16
4,vivo,Vivo T5x 5G,18999,66,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster",True,False,True,"Dimensity 7400 Turbo, Octa Core, 2.6 GHz Proce...",dimensity,...,128 GB inbuilt,7200 mAh Battery with 44W Fast Charging,7200.0,44.0,6.76 inches,120 Hz Display with Punch Hole,50 MP + 2 MP Dual Rear & 32 MP Front Camera,50.0,32.0,Android v16

In [212]:
# '120 Hz Display' থেকে শুধু '120' আলাদা করা
df1['refrash_rate'] = df1['refrash_rate'].str.extract('(\d+)').astype(float)

<>:2: SyntaxWarning: invalid escape sequence '\d'
<>:2: SyntaxWarning: invalid escape sequence '\d'
C:\Users\DELL\AppData\Local\Temp\ipykernel_25956\713439712.py:2: SyntaxWarning: invalid escape sequence '\d'
  df1['refrash_rate'] = df1['refrash_rate'].str.extract('(\d+)').astype(float)

In [213]:
df1.rename(columns={'refrash_rate': 'refresh_rate', 'spec scroe': 'spec_score'}, inplace=True)

In [214]:
# memory থেকে শুধু সংখ্যা বের করা
df1['memory'] = df1['memory'].str.extract('(\d+)').astype(float)

<>:2: SyntaxWarning: invalid escape sequence '\d'
<>:2: SyntaxWarning: invalid escape sequence '\d'
C:\Users\DELL\AppData\Local\Temp\ipykernel_25956\2566268053.py:2: SyntaxWarning: invalid escape sequence '\d'
  df1['memory'] = df1['memory'].str.extract('(\d+)').astype(float)

In [215]:
df1.info()

<class 'pandas.DataFrame'>
Index: 997 entries, 0 to 1019
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   brand_name             997 non-null    object
 1   model                  997 non-null    str
 2   price                  997 non-null    int64
 3   spec_score             997 non-null    int64
 4   sim                    997 non-null    str
 5   has_5G                 997 non-null    bool
 6   has_NFC                997 non-null    bool
 7   has_IR                 997 non-null    bool
 8   processor              997 non-null    str
 9   processor_brand        996 non-null    object
 10  processor_name         997 non-null    object
 11  num_core               941 non-null    object
 12  processor_speed        862 non-null    float64
 13  ram                    997 non-null    float64
 14  memory                 997 non-null    float64
 15  battery                997 non-null    str
 16  battery_capacity(mAh)  997 non-null    float64
 17  fast_charging(W)       941 non-null    float64
 18  screeen_size           997 non-null    object
 19  refresh_rate           948 non-null    float64
 20  camera                 997 non-null    str
 21  rear_camera            981 non-null    float64
 22  front_camera           979 non-null    float64
 23  os                     986 non-null    str
dtypes: bool(3), float64(8), int64(2), object(5), str(6)
memory usage: 206.6+ KB

In [216]:
df1.shape

(997, 24)

In [217]:
df1.head()

,brand_name,model,price,spec_score,sim,has_5G,has_NFC,has_IR,processor,processor_brand,...,memory,battery,battery_capacity(mAh),fast_charging(W),screeen_size,refresh_rate,camera,rear_camera,front_camera,os
0,oneplus,OnePlus Nord 6,38999,81,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...",True,True,True,"Snapdragon 8s Gen4, Octa Core, 3.2 GHz Processor",snapdragon,...,256.0,9000 mAh Battery with 80W Fast Charging,9000.0,80.0,6.78 inches,165.0,50 MP + 8 MP Dual Rear & 32 MP Front Camera,50.0,32.0,Android v16
1,samsung,Samsung Galaxy S25 Ultra,110000,89,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC",True,True,False,"Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...",snapdragon,...,256.0,5000 mAh Battery with 45W Fast Charging,5000.0,45.0,6.9 inches,120.0,200 MP Quad Rear & 12 MP Front Camera,200.0,12.0,Android v15
2,vivo,Vivo T5 Pro,29999,72,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, IR B...",True,False,True,"Snapdragon 7s Gen4, Octa Core Processor",snapdragon,...,128.0,9020 mAh Battery with 90W Fast Charging,9020.0,90.0,6.8 inches,120.0,50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,50.0,50.0,Android v16
3,samsung,Samsung Galaxy S25 FE,50743,77,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC",True,True,False,"Exynos 2400, Deca Core, 3.2 GHz Processor",exynos,...,128.0,4900 mAh Battery with 45W Fast Charging,4900.0,45.0,6.7 inches,120.0,50 MP + 12 MP + 8 MP Triple Rear & 12 MP Front...,50.0,12.0,Android v16
4,vivo,Vivo T5x 5G,18999,66,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster",True,False,True,"Dimensity 7400 Turbo, Octa Core, 2.6 GHz Proce...",dimensity,...,128.0,7200 mAh Battery with 44W Fast Charging,7200.0,44.0,6.76 inches,120.0,50 MP + 2 MP Dual Rear & 32 MP Front Camera,50.0,32.0,Android v16

In [218]:
# (\d+\.?\d*) এটি দশমিকসহ সংখ্যা খুঁজে বের করবে (যেমন: 6.78)
df1['screeen_size'] = df1['screeen_size'].str.extract('(\d+\.?\d*)').astype(float)

<>:2: SyntaxWarning: invalid escape sequence '\d'
<>:2: SyntaxWarning: invalid escape sequence '\d'
C:\Users\DELL\AppData\Local\Temp\ipykernel_25956\446452535.py:2: SyntaxWarning: invalid escape sequence '\d'
  df1['screeen_size'] = df1['screeen_size'].str.extract('(\d+\.?\d*)').astype(float)

In [219]:
df1.drop(columns=['sim'],inplace=True)

In [ ]:
df1.head()

,brand_name,model,price,spec_score,has_5G,has_NFC,has_IR,processor,processor_brand,processor_name,...,memory,battery,battery_capacity(mAh),fast_charging(W),screeen_size,refresh_rate,camera,rear_camera,front_camera,os
0,oneplus,OnePlus Nord 6,38999,81,True,True,True,"Snapdragon 8s Gen4, Octa Core, 3.2 GHz Processor",snapdragon,Snapdragon 8s Gen4,...,256.0,9000 mAh Battery with 80W Fast Charging,9000.0,80.0,6.78,165.0,50 MP + 8 MP Dual Rear & 32 MP Front Camera,50.0,32.0,Android v16
1,samsung,Samsung Galaxy S25 Ultra,110000,89,True,True,False,"Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...",snapdragon,Snapdragon 8 Elite for Galaxy,...,256.0,5000 mAh Battery with 45W Fast Charging,5000.0,45.0,6.90,120.0,200 MP Quad Rear & 12 MP Front Camera,200.0,12.0,Android v15
2,vivo,Vivo T5 Pro,29999,72,True,False,True,"Snapdragon 7s Gen4, Octa Core Processor",snapdragon,Snapdragon 7s Gen4,...,128.0,9020 mAh Battery with 90W Fast Charging,9020.0,90.0,6.80,120.0,50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,50.0,50.0,Android v16
3,samsung,Samsung Galaxy S25 FE,50743,77,True,True,False,"Exynos 2400, Deca Core, 3.2 GHz Processor",exynos,Exynos 2400,...,128.0,4900 mAh Battery with 45W Fast Charging,4900.0,45.0,6.70,120.0,50 MP + 12 MP + 8 MP Triple Rear & 12 MP Front...,50.0,12.0,Android v16
4,vivo,Vivo T5x 5G,18999,66,True,False,True,"Dimensity 7400 Turbo, Octa Core, 2.6 GHz Proce...",dimensity,Dimensity 7400 Turbo,...,128.0,7200 mAh Battery with 44W Fast Charging,7200.0,44.0,6.76,120.0,50 MP + 2 MP Dual Rear & 32 MP Front Camera,50.0,32.0,Android v16

In [220]:
df1.shape

(997, 23)

In [222]:
df1['price']=df1['price'].astype(int)

In [223]:
df1.info()

<class 'pandas.DataFrame'>
Index: 997 entries, 0 to 1019
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   brand_name             997 non-null    object
 1   model                  997 non-null    str
 2   price                  997 non-null    int64
 3   spec_score             997 non-null    int64
 4   has_5G                 997 non-null    bool
 5   has_NFC                997 non-null    bool
 6   has_IR                 997 non-null    bool
 7   processor              997 non-null    str
 8   processor_brand        996 non-null    object
 9   processor_name         997 non-null    object
 10  num_core               941 non-null    object
 11  processor_speed        862 non-null    float64
 12  ram                    997 non-null    float64
 13  memory                 997 non-null    float64
 14  battery                997 non-null    str
 15  battery_capacity(mAh)  997 non-null    float64
 16  fast_charging(W)       941 non-null    float64
 17  screeen_size           997 non-null    float64
 18  refresh_rate           948 non-null    float64
 19  camera                 997 non-null    str
 20  rear_camera            981 non-null    float64
 21  front_camera           979 non-null    float64
 22  os                     986 non-null    str
dtypes: bool(3), float64(9), int64(2), object(4), str(5)
memory usage: 198.8+ KB

In [226]:
df1.drop(columns=['processor'],inplace=True)

In [229]:
df1.rename(columns={'screeen_size': 'screen_size'}, inplace=True)

In [230]:
df1.head()

,brand_name,model,price,spec_score,has_5G,has_NFC,has_IR,processor_brand,processor_name,num_core,...,memory,battery,battery_capacity(mAh),fast_charging(W),screen_size,refresh_rate,camera,rear_camera,front_camera,os
0,oneplus,OnePlus Nord 6,38999,81,True,True,True,snapdragon,Snapdragon 8s Gen4,Octa Core,...,256.0,9000 mAh Battery with 80W Fast Charging,9000.0,80.0,6.78,165.0,50 MP + 8 MP Dual Rear & 32 MP Front Camera,50.0,32.0,Android v16
1,samsung,Samsung Galaxy S25 Ultra,110000,89,True,True,False,snapdragon,Snapdragon 8 Elite for Galaxy,Octa Core,...,256.0,5000 mAh Battery with 45W Fast Charging,5000.0,45.0,6.90,120.0,200 MP Quad Rear & 12 MP Front Camera,200.0,12.0,Android v15
2,vivo,Vivo T5 Pro,29999,72,True,False,True,snapdragon,Snapdragon 7s Gen4,Octa Core,...,128.0,9020 mAh Battery with 90W Fast Charging,9020.0,90.0,6.80,120.0,50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,50.0,50.0,Android v16
3,samsung,Samsung Galaxy S25 FE,50743,77,True,True,False,exynos,Exynos 2400,Deca Core,...,128.0,4900 mAh Battery with 45W Fast Charging,4900.0,45.0,6.70,120.0,50 MP + 12 MP + 8 MP Triple Rear & 12 MP Front...,50.0,12.0,Android v16
4,vivo,Vivo T5x 5G,18999,66,True,False,True,dimensity,Dimensity 7400 Turbo,Octa Core,...,128.0,7200 mAh Battery with 44W Fast Charging,7200.0,44.0,6.76,120.0,50 MP + 2 MP Dual Rear & 32 MP Front Camera,50.0,32.0,Android v16

In [240]:
# Samsung ফোনের ক্ষেত্রে যদি 'octa' থাকে তবে সেগুলোকে 'exynos' বা 'samsung' হিসেবে মার্ক করা
df1.loc[(df1['brand_name'] == 'samsung') & (df1['processor_brand'] == 'octa'), 'processor_brand'] = 'exynos'

# Huawei-এর ক্ষেত্রে 'kirin' হতে পারে
df1.loc[(df1['brand_name'] == 'huawei') & (df1['processor_brand'] == 'octa'), 'processor_brand'] = 'kirin'

In [243]:
df1.loc[(df1['brand_name'] == 'oneplus') & (df1['processor_brand'] == 'octa'), 'processor_brand'] = 'snapdragon'

In [247]:
# Replace 'octa' with 'unknown' or 'other' to keep the brand column clean
df1['processor_brand'] = df1['processor_brand'].replace('octa', 'unknown')

In [ ]:
# Example: If you know specific models use a certain brand
df1.loc[df1['model'].str.contains('Vivo T5 Ultra', case=False), 'processor_brand'] = 'dimensity'

In [256]:
df1.loc[df1['processor_brand'] == 'unknown', 'num_core'] = 'Octa Core'

In [257]:
df1.info()

<class 'pandas.DataFrame'>
Index: 997 entries, 0 to 1019
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   brand_name             997 non-null    object
 1   model                  997 non-null    str
 2   price                  997 non-null    int64
 3   spec_score             997 non-null    int64
 4   has_5G                 997 non-null    bool
 5   has_NFC                997 non-null    bool
 6   has_IR                 997 non-null    bool
 7   processor_brand        996 non-null    object
 8   processor_name         997 non-null    object
 9   num_core               980 non-null    object
 10  processor_speed        862 non-null    float64
 11  ram                    997 non-null    float64
 12  memory                 997 non-null    float64
 13  battery                997 non-null    str
 14  battery_capacity(mAh)  997 non-null    float64
 15  fast_charging(W)       941 non-null    float64
 16  screen_size            997 non-null    float64
 17  refresh_rate           948 non-null    float64
 18  camera                 997 non-null    str
 19  rear_camera            981 non-null    float64
 20  front_camera           979 non-null    float64
 21  os                     986 non-null    str
dtypes: bool(3), float64(9), int64(2), object(4), str(4)
memory usage: 191.0+ KB

In [258]:
df1.to_csv('mobile2',index=False)